#include "structures.h"

// Remember to take into account that you might have the right object earlier than normal if you are loading a save game!
// take it into account if you can!
// Also remember that SFX_FLASH needs BOOMSFX on the HAS_xxx list

#ifdef LOCATION_IS_0
// just story                                 //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                    //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   PP_PHOENIX,  0,  PP_NONE    | CMD_ADDEV,     "?????? ??????? June 9th, 8:??PM"  },
{   EV_NONE,     0,  PP_NONE    | CMD_MUSPROLOG, "Time for negotiations..."  },
{   EV_BADGE,    0,  PP_NONE    | CMD_ADDEV,     "Forget it, I'm not doing it!"  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "Do it or else!"  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "I don't care about that anymore..."  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "Besides... I have a better idea..."  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "WHAT?!"  },
{   EV_MAGATAMA, 0,  PP_NONE    | CMD_ADDEV,     "Enjoy the parting gift!"  },
{   EV_NONE,     1,  PP_NONE    | CMD_STOPMUS,   ""  },
{   EV_NONE,     1,  PP_NONE    | CMD_FLASH,     ""  },
{   EV_NONE,     1,  PP_NONE    | CMD_BLACK,     "June 9th, 9:43PM Wright and Co. Law Offices" },
{   EV_NONE,     3,  PP_NONE    | CMD_MUSSTEEL,  "(*ring*)"  },
{   EV_NONE,     3,  PP_PHOENIX | CMD_STOPMUS,   "Phoenix Wright and Co. Office. \"Defending YOU like it's nuttin', baby\"!"   },
{   EV_NONE,     3,  PP_PHOENIX | CMD_NONE,      "...No ...sorry... I-I don't need a vegetable dicer..." },
{   EV_NONE,     3,  PP_PHOENIX | CMD_NONE,      "I'm sure that...ugh..." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "That silly slogan Maya came up with must be what's making business this slow, I should really have it revised..." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Scratch that! I NEED to have it revised! What a ridiculous slogan! Who are we trying to attract, grade school students?" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "I guess it is a good sign though..." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "The fewer people who need an attorney the fewer problems there are in the world." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Unfortunately sunshine and smiles don't pay the bills." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Guess I can at least call it early tonight." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_BOOMSFX,   "ARGH!" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_MUSSUSPENSE,"W-what's going on!?"},
{   EV_NONE,     2,  PP_PHOENIX | CMD_FLASH,     "I can't move my body!" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "(Wait, is my hand fading away?!)" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Getting...Dizzy... am I... dying...?" },
{   1,           2,  PP_PHOENIX | CMD_ENDSTORY,  "" }   // go to location 1 (negative value to flag)
};
#endif

#ifdef LOCATION_IS_1
//      story                                 //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                    //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   EV_NONE,     4,  PP_NONE    | CMD_BLACK,     "?????????????? June 9th, 9:45PM"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "Ughhhhh..."  },
{   EV_NONE,     4,  PP_UNKNOWN | CMD_BLACK,     "Hey! Who the heck are you?!"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(...Whose voice is that?)"  },
{   EV_NONE,     4,  PP_UNKNOWN | CMD_BLACK,     "For that matter WHAT the heck are you?"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(\"What am I?\" What kind of question is that, does she mean my profession?)"  },
{   EV_NONE,     4,  PP_UNKNOWN | CMD_BLACK,     "I wanted the best Defense Attorney in Equestria, not some... porcupine thing."  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(*Sigh* Does my hair really look like a porcupine...?)"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(My muscles are coming to, I think I can open my eyes.)"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_NONE,      "Huh? Where am I?"  },
{   EV_NONE,     5,  PP_UNKNOWN | CMD_NONE,      "Hey! You're a human, aren't you?"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "Yeah... I'm a human..."  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_FLASH,     "WAIT WHAT?!"  },
{   EV_NONE,     6,  PP_UNKNOWN | CMD_MUSTRUCY,  "A human in Equestria, that's amazing!"  },
{   EV_NONE,     6,  PP_PHOENIX | CMD_NONE,      "Y-YOU'RE A TALKING HORSE!"  },
{   EV_NONE,     7,  PP_UNKNOWN | CMD_NONE,      "Excuse me! I am not a horse, I happen to be a pony."  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "OH! Okay! A talking PONY. That explains everything!"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "I must be in a dream... a really REALLY bad dream."  },
{   EV_NONE,     7,  PP_UNKNOWN | CMD_NONE,      "I'm pretty sure you're not, let's conduct an experiment..."  },
{   EV_NONE,     7,  PP_PHOENIX | CMD_FLASH,     "Ow! What was that for?!"  },
{   EV_NONE,     8,  PP_UNKNOWN | CMD_NONE,      "You acknowledged pain, therefore that definitely means you aren't dreaming."  },
{   EV_NONE,     8,  PP_PHOENIX | CMD_NONE,      "(This thing has a really sick sense of humor.)"  },
{   EV_NONE,     5,  PP_UNKNOWN | CMD_NONE,      "Wait... are you a defense attorney?"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "Of course I am!"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "(Why am I talking to it?!)"  },
{   EV_NONE,     9,  PP_UNKNOWN | CMD_NONE,      "Oh... oops... my mistake."  },
{   EV_NONE,     9,  PP_PHOENIX | CMD_NONE,      "What do you mean \"oops\"?"  },
{   EV_NONE,     7,  PP_UNKNOWN | CMD_NONE,      "Well, I cast a spell to call upon \"The Greatest Defense Attorney in Equestria\""  },
{   EV_NONE,     7,  PP_PHOENIX | CMD_NONE,      "What is Equestria?"  },
{   EV_NONE,    10,  PP_UNKNOWN | CMD_NONE,      "The name of this country."  },
{   EV_NONE,    11,  PP_PHOENIX | CMD_NONE,      "But I'm not FROM this country!"  },
{   EV_NONE,    10,  PP_UNKNOWN | CMD_NONE,      "I must have left out the \"Equestria\" part when I cast the spell."  },
{   EV_NONE,     9,  PP_UNKNOWN | CMD_NONE,      "I guess I accidentally called upon \"The Greatest Defense Attorney\" period."  },
{   EV_NONE,     9,  PP_UNKNOWN | CMD_NONE,      "Go figure, huh?"  },
{   EV_T_SNDBCK, 9,  PP_PHOENIX | CMD_ADDPROMPT, "Send me back"  },
{   EV_T_WHORU,  9,  PP_PHOENIX | CMD_ADDPROMPT, "Who are you?"  },
{   EV_NONE,     9,  PP_PHOENIX | CMD_NONE,      "(Oh cosmos, you flatter me.)"  },
{   EV_NONE,     9,  PP_PHOENIX | CMD_SELPROMPT, ""  },

{  EV_T_SNDBCK,  5 , PP_PHOENIX  | CMD_NONE,     "Well, can you please send me back... like RIGHT NOW?!"  },
{   EV_NONE,     10, PP_UNKNOWN  | CMD_NONE,     "Sure thing..."  },
{   EV_NONE,     6 , PP_UNKNOWN  | CMD_NONE,     "Actually... this is perfect!"  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "(Oh please don't tell me this is going where I think it is...)"  },
{   EV_NONE,     10, PP_UNKNOWN  | CMD_NONE,     "You see I am in need of a really good defense attorney..."  },
{   EV_NONE,     10, PP_PHOENIX  | CMD_NONE,     "(... aaaaaaand it does go where I think it is...)"  },
{   EV_NONE,     6 , PP_UNKNOWN  | CMD_NONE,     "And you just happen to be here..."  },
{   EV_NONE,     12, PP_PHOENIX  | CMD_NONE,     "Actually, you kidnapped me with your freaky spell, remember..."  },
{   EV_NONE,     7 , PP_UNKNOWN  | CMD_NONE,     "A minor distinction..."  },
{   EV_NONE,     7 , PP_PHOENIX  | CMD_NONE,     "MINOR!?"  },
{   EV_NONE,     6 , PP_UNKNOWN  | CMD_NONE,     "Yes... but would you be willing to represent my friend?"  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "...To be honest... I'm still shocked I am in a library talking to a purple hors-err I mean... pony..."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "Can you just send me home, please, and get someone else to do it?"  },
{   EV_NONE,     13, PP_UNKNOWN  | CMD_NONE,     "Look, I really need help... my friend's life is at stake here..."  },
{   EV_NONE,     13, PP_UNKNOWN  | CMD_SELPROMPT,""  },

{  EV_T_SNDBCK2, 5 , PP_PHOENIX  | CMD_NONE,     "Well, can you please send me back... like RIGHT NOW?!"  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "Sure thing..."  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Actually... this is perfect!"  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "(Oh please don't tell me this is going where I think it is...)"  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "You see I am in need of a really good defense attorney..."  },
{   EV_NONE,     10, PP_PHOENIX  | CMD_NONE,     "(... aaaaaaand it does go where I think it is...)"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "And you just happen to be here..."  },
{   EV_NONE,     12, PP_PHOENIX  | CMD_NONE,     "Actually, you kidnapped me with your freaky spell, remember..."  },
{   EV_NONE,     7 , PP_TWILIGHT | CMD_NONE,     "A minor distinction..."  },
{   EV_NONE,     7 , PP_PHOENIX  | CMD_NONE,     "MINOR!?"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Yes... but would you be willing to represent my friend?"  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "...Honest... I'm still shocked I am in a library talking to a purple hors-err I mean... pony..."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "Can you just send me home, please, and get someone else to do it?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Look, I really need help... my friend's life is at stake here..."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_SELPROMPT,""  },

{  EV_T_WHORU,   5 , PP_PHOENIX  | CMD_NONE,     "Let me just get my head together. This is a little too much for me."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "First off, who are you and where am I?"  },
{   PP_TWILIGHT, 10, PP_TWILIGHT | CMD_ADDEV,    "My name is Twilight Sparkle. I'm a disciple of \"Princess Celestia\", the monarch of this land."  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "I am chronicling the magic of friendship for her and you're in the town of Ponyville."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "Celestia? Magic of Friendship? Ponyville?... Wait a minute, are you saying there are more talking ponies?!"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Mhm, almost all of Ponyville's inhabitants are ponies."  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "Oh joy, this keeps getting better and better."  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "Hey, I know! Be right back!"  },
{   EV_NONE,     4 , PP_PHOENIX  | CMD_NONE,     "(Whoa! Is she moving books around with that horn?)"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Found it! Here you go! You're new here, so you can read this... uh... \"detailed\" encyclopedia of the different ponies in Equestria."  },
{   EV_NONE,     14, PP_PHOENIX  | CMD_NONE,     "Hmmm... wait! This says it's \"For early ages\" on the cover!"  },
{   EV_NONE,     14, PP_PHOENIX  | CMD_NONE,     "This is a children's book!"  },
{   EV_NONE,     9 , PP_TWILIGHT | CMD_NONE,     "Well you see... this stuff is kind of common knowledge."  },
{   EV_FILLIES,  15, PP_NONE     | CMD_ADDEV,    "The Fillies Guide to Ponies: Earth Ponies founded Land. Unicorns use magic. Pegasi soar through the air."  },
{   EV_NONE,     9 , PP_PHOENIX  | CMD_NONE,     "You call this detailed! I read the whole book cover to cover in ten seconds flat..."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_STOPMUS,  "*Sigh*"  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Hey... I'm sorry. I guess I shouldn't look a gift horse in the mouth."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "(Should I have said Pony there, I wonder...?)"  },
{   EV_T_SNDBCK, EV_T_SNDBCK2, PP_PHOENIX  | CMD_CHANGEPROMPT, ""  }, // update target of SNDBCK since we know the name now
{   EV_T_CRIME,  13, PP_PHOENIX  | CMD_ADDPROMPT,"What was the crime?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "No, it's not that. It's my friend... I know she is not guilty but she is going to be punished for a crime she didn't even commit."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_SELPROMPT,""  },

{  EV_T_CRIME,   13, PP_PHOENIX  | CMD_NONE,     "What kind of crime is she being accused of?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Murder..."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "(Surprise, surprise...)"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Murder never happens in Ponyville, or Equestria for that matter, so the punishment is very severe."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "What is the punishment?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Banishment..."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Well that isn't so bad compared to-"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "To the moon... or even the sun..."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "I have convinced the Princess to go easy on her but she will have no choice if the verdict ends up being guilty."  },
{   EV_T_DETAIL, 9,  PP_PHOENIX  | CMD_ADDPROMPT,"Any details?"  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "(And forget what I just said, sheesh! If being sent to the sun is \"going easy on someone\" then remind me never to do anything bad in this place.)"  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_SELPROMPT,""  },

{   EV_T_DETAIL, 13, PP_PHOENIX  | CMD_NONE,     "So...uh...Twilight, do you know any details about the crime?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Not much, all I know was my friend was near the scene of the crime when the murder took place. That is why she's the prime suspect."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Where is she right now?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "In the Ponyville Detention Center."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Have you spoken with her since?"  },
{   EV_NONE,     5 , PP_TWILIGHT | CMD_NONE,     "I would but the guards won't let me in."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "They won't let you in? Why not?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "I can only get in there with a Defense Attorney which is why I was trying to call one."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Okay then. Since I'm a Defense Attorney, let's go to this Detention Center."  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_MUSTRUCY, "Really! So you'll take the case?!"  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "Hey hey... I haven't decided that yet. I just thought the least I could do is help you get in to speak with your friend."  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Thank you for your kindness, Phoenix Wright."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_STOPMUS,  "How did you know my name? I haven't introduced myself yet..."  },
{   EV_NONE,     16, PP_TWILIGHT | CMD_NONE,     "Oh-uh... I did... uh.. a quick identification spell."  },
{   EV_NONE,     16, PP_PHOENIX  | CMD_NONE,     "Identification spell?"  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "Yeah! An identification spell! Anyway, let me prepare a few things, then we can go to the Detention Center."  },
{   EV_NONE,     4,  PP_PHOENIX  | CMD_NONE,     "(After I get her inside there with her friend, I'll let her off easy and make her send me back home. There is no way I'm taking a case this weird...)"  },
{   2,           4 , PP_PHOENIX  | CMD_ENDSTORY, ""  }
};

#endif

#ifdef LOCATION_IS_2
//      story                                    //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                       //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   EV_NONE,    17,     PP_NONE     | CMD_NONE,     "Ponyville June 9th, 10:05PM"   },
{   EV_NONE,    17,     PP_PHOENIX  | CMD_NONE,     "I have never felt like such a minority in my life!"    },
{   EV_NONE,    18,     PP_TWILIGHT | CMD_NONE,     "Oh, it wasn't that bad."   },
{   EV_NONE,    18,     PP_PHOENIX  | CMD_NONE,     "All those ponies were gawking at me the whole way here!"   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_NONE,     "Mr. Wright, humans have almost never been seen in Equestria."   },
{   EV_NONE,    18,     PP_TWILIGHT | CMD_NONE,     "In fact you may be the first one in Ponyville."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "You should be honored!"   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_NONE,     "(Honored? Strolling around a town infested with candy colored equines...)"   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_NONE,     "(Yeah, maybe I'd feel honored if I was... Oh, I dunno... a five year old girl!)"   },

{   EV_T_HUMAN, 20,     PP_PHOENIX  | CMD_ADDPROMPT, "How did you know?"  },
{   EV_T_NOHUMAN, 20,   PP_PHOENIX  | CMD_ADDPROMPT, "Let it go"  },
{   EV_NONE,     20,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_HUMAN, 20,     PP_PHOENIX  | CMD_NONE,     "So how did you know I was a human?"   },
{   EV_NONE,    21,     PP_TWILIGHT | CMD_NONE,     "I read a lot!"   },
{   EV_NONE,    21,     PP_TWILIGHT | CMD_NONE,     "I've read almost every book in my library five times over and I am familiar with a lot of different species:"   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "Chimeras, Trolls, Basilisks, Goblins, et cetera, et cetera."   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_NONE,     "(Wait!? You're telling me she has read every book in that gigantic library FIVE TIMES?!)"   },

{   EV_T_NOHUMAN, 19,   PP_TWILIGHT | CMD_NONE,     "Anyway we're here, Phoenix."   },
{   PP_GUARD,   22,     PP_GUARD    | CMD_ADDEV,    "Halt! Only a lawyer can enter the detention center."   },
{   EV_NONE,    18,     PP_TWILIGHT | CMD_NONE,     "Well, go on..."   },
{   EV_NONE,    22,     PP_PHOENIX  | CMD_NONE,     "Uh... Hi guys, I'm a lawyer..."   },
{   EV_NONE,    22,     PP_GUARD    | CMD_NONE,     "Identification!"   },

{   EV_NONE,    22,     PP_GUARD    | CMD_SHOWEV,   "Present your identification"   },
{   EV_BADGE,EV_T_LAWYERBADGE, PP_GUARD|CMD_JUMPIFSHOW, "" }, 
{  EV_E_BADGE,EV_T_RIGHTBADGE, PP_GUARD|CMD_JUMPIFSHOW, "" }, 
{   EV_T_NOBADGE,22,    PP_GUARD    | CMD_JUMP,     "" }, 

{   EV_T_LAWYERBADGE, 22, PP_PHOENIX| CMD_NONE,     "Ah!... Right here!"   },
{   EV_NONE,    23,     PP_PHOENIX  | CMD_NONE,     "(Never leave home without it!)"   },
{   EV_NONE,    23,     PP_GUARD    | CMD_NONE,     "What is that?"   },
{   EV_NONE,    23,     PP_GUARD    | CMD_NONE,     "Is that a toy? You look a little old to be playing with toys."   },
{   EV_NONE,    23,     PP_PHOENIX  | CMD_NONE,     "(Next time I am leaving it at home...)"   },

{   EV_T_NOBADGE,22,    PP_GUARD    | CMD_NONE,     "You cannot pass without valid Equestrian identification."   },
{   EV_NONE,    22,     PP_PHOENIX  | CMD_NONE,     "But I don't have any..."   },
{   EV_NONE,    22,     PP_GUARD    | CMD_NONE,     "Then beat it Spiky!"   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE,     "Twilight! They're not letting me in."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "Oh that's right, Mr. Wright! I was supposed to give you this."   },
{   EV_NONE,    24,     PP_TWILIGHT | CMD_CLRPROMPT,"The princess ordered me to give you this earlier today. A permit to defend in Equestria."   },

{   EV_T_QUESTIONBADGE,24,PP_PHOENIX| CMD_ADDPROMPT,"That seems odd..."   },
{   EV_T_NOQBADGE,24,   PP_PHOENIX | CMD_ADDPROMPT, "That's fine."        },
{   EV_NONE,     24,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{EV_T_QUESTIONBADGE,24, PP_PHOENIX  | CMD_NONE,     "I see... wait..."   },
{   EV_NONE,    25,     PP_PHOENIX  | CMD_NONE,     "I thought you accidentally brought me here. How could your princess have had that prepared for me?"   },
{   EV_NONE,    26,     PP_TWILIGHT | CMD_NONE,     "O-oh uh What I meant was... I had my assistant Spike prepare it before we left."   },
{   EV_NONE,    26,     PP_PHOENIX  | CMD_NONE,     "Spike? I didn't see anyone else in that library..."   },
{   EV_NONE,    25,     PP_TWILIGHT | CMD_NONE,     "He was sleeping. It's late as you can see, I had to wake him up and have him prepare it. That's why it took a little while to leave."   },
{   EV_NONE,    27,     PP_TWILIGHT | CMD_NONE,     "I'll properly introduce you to him later."   },
{   EV_NONE,    28,     PP_PHOENIX  | CMD_NONE,     "You prepared a permit in twenty minutes? I find that a little fishy..."   },
{   EV_NONE,    29,     PP_TWILIGHT | CMD_NONE,     "Save the questions for my friend, just take the badge!"   },
{   EV_NONE,    29,     PP_PHOENIX  | CMD_NONE,     "(This isn't helping me accept your request, you know...)"   },

{ EV_T_NOQBADGE,30,     PP_PHOENIX  | CMD_NONE,     "Equestrian Attorney Badge. A heart shaped badge that gives all the privileges of an Equestrian defense attorney."  },
{ EV_E_BADGE,   19,     PP_PHOENIX  | CMD_ADDEV,    "A heart..."   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE,     "(I feel my masculinity going... going... gone.)"   },
{   EV_NONE,    31,     PP_TWILIGHT | CMD_NONE,     "Come on, hurry up! Visiting hours are almost over."   },
{   EV_NONE,    31,     PP_PHOENIX  | CMD_NONE,     "Alright, alright! No need to shove me..."   },
{   EV_NONE,    32,     PP_PHOENIX  | CMD_NONE,     "Okay... guys here it is..."   },
{   EV_NONE,    32,     PP_PHOENIX  | CMD_NONE,     "(This is so degrading...)"   },

{ EV_T_RIGHTBADGE,32,   PP_GUARD    | CMD_NONE,     "Permission granted, you may enter."   },
{   EV_NONE,    32,     PP_PHOENIX  | CMD_NONE,     "Phew... alrighty!"   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE,     "Come on Twilight, you can go speak with your friend now."   },
{   EV_NONE,    33,     PP_TWILIGHT | CMD_NONE,     "Sorry Phoenix..."   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "Sorry? About what?"   },
{   EV_NONE,    33,     PP_TWILIGHT | CMD_NONE,     "I am not allowed in, only attorneys are allowed to speak with suspects..."   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "But you said..."   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_NONE,     "I know I said I'd talk to her but it'd be better if you got all the details about the crime to make your judgement."   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_NONE,     "Just please hear her out... if you don't want to do it after that..."   },
{   EV_NONE,    33,     PP_TWILIGHT | CMD_NONE,     "I'll send you back to where you came from..."   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_CLRPROMPT, "But I-"   },

{   EV_T_CONCERN,24,    PP_PHOENIX  | CMD_ADDPROMPT, "Concerned..."   },
{   EV_T_NOCONCERN,24,  PP_PHOENIX  | CMD_ADDPROMPT, "See what it's all about."        },
{   EV_NONE,     24,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_CONCERN, 33,   PP_PHOENIX  | CMD_NONE,     "(Should I really be doing this...?)"   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "(Should I really be meddling in some other world's affair...?)"   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "(Maybe I should at least hear what all this fuss is about...)"   },

{ EV_T_NOCONCERN, 33,   PP_PHOENIX  | CMD_NONE,     "Sigh... Fine..."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "Thank you so much, Mr. Wright."   },
{   3,          20,     PP_NONE     | CMD_ENDSTORY, ""  }   // go to location 3

};
#endif

#ifdef LOCATION_IS_3
//      story                                    //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                       //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901

{   EV_NONE,    34,     PP_NONE     | CMD_NONE,     "Ponyville Detention Center June 9th, 10:15PM"      },
{   EV_NONE,    34,     PP_PHOENIX  | CMD_NONE,     "Okay, so where is Twilight's friend?"      },
{   EV_NONE,    35,     PP_UNKNOWN  | CMD_CHIMESFX, "Hey!"      },
{   EV_NONE,    35,     PP_PHOENIX  | CMD_NONE,     "Eh?! What did I do?!"      },
{   EV_NONE,    36,     PP_UNKNOWN  | CMD_NONE,     "I don't think they allow animals in here, you should get out before they toss you in here too."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Look, I am not an animal. I'm a human being!"      },
{   EV_NONE,    37,     PP_UNKNOWN  | CMD_NONE,     "Oh... I didn't mean you, I meant that thing on your head."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "(If someone makes fun of my hair ONE more time...)"      },
{   EV_NONE,    37,     PP_UNKNOWN  | CMD_MUSGUILTY,"So I'm guessing you're my lawyer, huh?"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "Yes, Twilight Sparkle sent me..."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_BOOMSFX,  "Wait! No! I haven't agreed to anything yet!"      },
{   EV_NONE,    38,     PP_UNKNOWN  | CMD_NONE,     "Geez, Twilight knows how to pick 'em..."      },
{   EV_NONE,    36,     PP_UNKNOWN  | CMD_NONE,     "What are you doing here then?"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "I just want information regarding the crime you are being accused of."      },

{   EV_T_RDNAME, 36,    PP_PHOENIX  | CMD_ADDPROMPT, "What's your name?"    },
{   EV_NONE,     36,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_RDNAME,36,     PP_PHOENIX  | CMD_NONE,     "Let's start off with your name..."      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "I'm Rainbow Dash, best flier in Ponyville! Soon to be a household name in all of Equestria!"      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "Line up for my autograph starts over there!"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "(Twilight Sparkle? Rainbow Dash?)"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "(Is it me or are their names starting to sound like flavors of ice cream?)"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "I am Phoenix Wright, best attorney in the... universe... apparently..."      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_NONE,     "Phoenix?"      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_NONE,     "Sweet name but it could sound cooler..."      },
{   EV_NONE,    39,     PP_PHOENIX  | CMD_NONE,     "Uuhh... \"cooler\"?"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "I think I'll call you \"Nix\", that sounds cool!"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "(Another strange name I can add to my nickname checklist.)"      },

{   EV_T_EARTHP, 36,    PP_PHOENIX  | CMD_ADDPROMPT, "You're an earth pony?"   },
{   EV_T_UNIP,   36,    PP_PHOENIX  | CMD_ADDPROMPT, "You're a unicorn?"   },
{   EV_T_PEGASUSP,36,   PP_PHOENIX  | CMD_ADDPROMPT, "You're a pegasus?"   },
{   EV_T_NOPONY, 36,    PP_PHOENIX  | CMD_ADDPROMPT, "Why are you in here?"    },
{   EV_NONE,     36,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{ EV_T_EARTHP,  36,     PP_PHOENIX  | CMD_NONE,     "Hmmm, so you are an... earth pony, correct?"      },
{   EV_NONE,    41,     PP_RAINBOW  | CMD_NONE,     "What the hay are you talking about? I'm not an earth pony, I'm a pegasus!"      },
{EV_T_BADGUESS, 41,     PP_RAINBOW  | CMD_JUMP,     ""      },

{   EV_T_UNIP,  36,     PP_PHOENIX  | CMD_NONE,     "Hmmm, so you are a... unicorn pony, correct?"      },
{   EV_NONE,    41,     PP_RAINBOW  | CMD_NONE,     "What the hay are you talking about? I'm not a unicorn, I'm a pegasus!"      },
{EV_T_BADGUESS, 41,     PP_RAINBOW  | CMD_JUMP,     ""      },

{ EV_T_PEGASUSP,36,     PP_PHOENIX  | CMD_NONE,     "Hmmm, so you are a... pegasus, correct?"      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "That's right! The BEST pegasus! Good for you, Nix!"      },
{EV_T_NOPONY,   41,     PP_RAINBOW  | CMD_JUMP,     ""      },

{EV_T_BADGUESS, 41,     PP_PHOENIX  | CMD_NONE,     "(It's kinda sad I couldn't get down a book with twelve words.)"      },

{ EV_T_NOPONY,  41,     PP_PHOENIX  | CMD_NONE,     "Uhh... never mind that. Why are you in here?"      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_NONE,     "Well, I guess I can tell you all I know..."      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_CLRPROMPT,"You see, last night a pegasus named \"Ace Swift\" was killed in the Everfree Forest."      },

{   EV_T_ACE,   36,    PP_PHOENIX  | CMD_ADDPROMPT, "Ace Swift"    },
{   EV_NONE,    36,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_ACE,   36,     PP_PHOENIX  | CMD_NONE,     "Do you know anything about him?"      },
{   PP_ACE2,    37,     PP_RAINBOW  | CMD_ADDEV,    "Sure do, he was a hot shot racer expected to win the \"Equestrian 500\"."      },

{   EV_T_EQ500, 36,    PP_PHOENIX  | CMD_ADDPROMPT, "Equestrian 500"    },
{   EV_NONE,    36,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_EQ500, 37,     PP_PHOENIX  | CMD_NONE,     "\"Equestrian 500\"?"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "A grueling race for pegasi, enduring a five hundred mile journey around Equestria."      },
{   EV_EQ500,   37,     PP_RAINBOW  | CMD_ADDEV,    "He was the top pick to win the whole thing."      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "Dont worry though..."      },

{   EV_T_DONTWORRY, 36, PP_PHOENIX  | CMD_ADDPROMPT, "Don't worry?"    },
{   EV_T_HOWDIE, 36,    PP_PHOENIX  | CMD_ADDPROMPT, "How did he die?"    },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_DONTWORRY, 39, PP_PHOENIX  | CMD_NONE,     "\"Don't worry\"? About what?"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "I still would have won even if he were still alive, ha!"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "Let me guess, you were planning on entering that race as well?"      },
{   EV_NONE,    42,     PP_RAINBOW  | CMD_NONE,     "Of course! The winner gets special lessons from the Wonderbolts!"      },
{   EV_NONE,    42,     PP_PHOENIX  | CMD_NONE,     "Who are \"The Wonderbolts\"?"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "You don't know who the Wonderbolts are?"      },
{   EV_NONE,    35,     PP_RAINBOW  | CMD_NONE,     "You living under a rock or something?!"      },
{   EV_NONE,    35,     PP_PHOENIX  | CMD_NONE,     "Hey, I'm new here! Cut me some slack!"      },
{   EV_NONE,    43,     PP_RAINBOW  | CMD_NONE,     "*Sigh*"      },
{   EV_NONE,    41,     PP_RAINBOW  | CMD_NONE,     "\"THE\" Wonderbolts are only the most coolest ponies in all of Equestria!"      },
{   EV_NONE,    41,     PP_RAINBOW  | CMD_NONE,     "They are the Princess' personal aerial acrobatic team. The stunts they perform are nine degrees of cool!"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "You see, I've been trying to get in their group forever and the Equestrian 500 is my ticket to show off my slick moves to them."      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "I'd do anything to get that chance!"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "(Thank you for effectively establishing motive for yourself, Ms. Dash, this helps your case so much...)"      },

{   EV_NONE,    36,     PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_HOWDIE, 37,    PP_PHOENIX  | CMD_NONE,     "So how did this guy die?"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "Pony."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Wha...?"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "\"How did this pony die?\" is what you mean, Nix."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "(Well excuse me, I didn't take \"Hooked on Ponyics\")"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "The point is, how did he die?"      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_NONE,     "How should I know? I didn't do it..."      },

{   EV_T_ARREST,36,    PP_PHOENIX  | CMD_ADDPROMPT, "Arrest?"    },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_ARREST,40,     PP_PHOENIX  | CMD_NONE,     "Then why did they take you in?"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "I just happened to be flying near the Everfree Forest that night..."      },
{   EV_NONE,    35,     PP_RAINBOW  | CMD_NONE,     "Then those chuckleheads burst into my house and brought me here, saying \"I did it\"!"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "They even said that they had lots of proof but I would never do that to another pony!"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "They just took you in like that?"      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_STOPMUS,  "They said they are going to banish me..."      },
{   EV_NONE,    45,     PP_PHOENIX  | CMD_NONE,     "So I heard..."      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_MUSELEGY, "Everyone thinks I did it, everyone!"      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_NONE,     "The Wonderbolts probably hate me..."      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "But you believe me, right?"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Well, I-I guess, but not everyone thinks you did it..."      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_NONE,     "Huh?"      },
{   EV_NONE,    40,     PP_PHOENIX  | CMD_NONE,     "Your friend Twilight seems to have faith in you, otherwise I wouldn't be in this mess..."      },
{   EV_NONE,    44,     PP_RAINBOW  | CMD_NONE,     "Heh, you're right I guess. Twilight's a real pal..."      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "What do you mean by \"mess\", anyway?"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "As you can probably guess: I'm not from Equestria."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Your purple friend pulled me out of my world because she accidentally called the \"Greatest Defense Attorney\"... and that happened to be me."      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "Awesome! It's only fitting, the best pegasus ever gets the best lawyer ever!"      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "You were destined to defend me!"      },
{   EV_NONE,    39,     PP_PHOENIX  | CMD_NONE,     "(This one's ego is larger than Detective Gumshoe's appetite for instant noodles.)"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "Nix, as much as I hate asking for help..."      },
{   EV_NONE,    44,     PP_RAINBOW  | CMD_NONE,     "Can you PAH-LEEES be my Attorney?"      },
{   EV_NONE,    44,     PP_PHOENIX  | CMD_CLRPROMPT,"(I feel kind of sorry for her, she sounds like she is telling the truth and I want to say yes... but should I...?)"      },

{   EV_T_BELIEVE,36,    PP_PHOENIX  | CMD_ADDPROMPT, "Believe her"    },
{   EV_T_MAKESURE,36,   PP_PHOENIX  | CMD_ADDPROMPT, "Make sure"    },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_BELIEVE,44,    PP_PHOENIX  | CMD_NONE,     "Well... oh, wait a minute!"      },
{   EV_NONE,    46,     PP_PHOENIX  | CMD_NONE,     "(I believe her but I better make sure...)"      },
{   EV_T_CHECKDASH, 36, PP_PHOENIX  | CMD_JUMP,     ""  },

{   EV_T_MAKESURE, 47,  PP_PHOENIX  | CMD_NONE,     "(I think I better make sure...)"  },

{   EV_T_CHECKDASH, 47, PP_PHOENIX  | CMD_NONE,     "Magatama: A gift from Maya. Allows me to see if anyone is hiding any deep secret in their heart from me."  },
{   EV_NONE,    48,     PP_RAINBOW  | CMD_NONE,     "Is that a toy? You look a little old to be playing with toys, Nix."      },
{   EV_NONE,    49,     PP_PHOENIX  | CMD_NONE,     "Look, Rainbow Dash, I am going to ask you this and I want you to tell me the absolute 100% truth!"      },
{   EV_NONE,    49,     PP_PHOENIX  | CMD_STOPMUS,  "Did you have ANYTHING to do with the death of \"Ace Swift\"?"      },
{   EV_NONE,    50,     PP_RAINBOW  | CMD_CRASHSFX, "I told you... I DIDN'T KILL ANYPONY!"      },
{   EV_NONE,    50,     PP_PHOENIX  | CMD_NONE,     "..."      },
{   EV_NONE,    49,     PP_PHOENIX  | CMD_NONE,     "(Nothing... it's certain then. She really didn't do it.)"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Okay Rainbow Dash..."      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "What? Why did you go all silent there?"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "I've decided to take your case, I trust you."      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_MUSGUILTY,"Yes! Alright! I know you can do it Nix!"      },
{   EV_NONE,    39,     PP_PHOENIX  | CMD_NONE,     "I suppose the first thing I should do is investigate the scene of the crime for some evidence to prove your innocence. Where was it again?"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "A clearing in the Everfree Forest."      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "Everfree Forest?"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "Yeah, it's about fifteen minutes from Fluttershy's house."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Fluttershy... huh..."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "(Probably another pony...)"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "Well good luck Nix, you may look a little strange but you're okay in my book!"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "(\"I\" look a little strange?! Coming from the \"Roy G Biv\" pony with wings, you look strange even by Ponyville standards!)"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "Oh... right, there was one more question I wanted to ask you..."      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_CLRPROMPT,"Shoot!"      },

{   EV_T_WHYTHERE,36,   PP_PHOENIX  | CMD_ADDPROMPT, "What were you doing there?"    },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_WHYTHERE, 40,  PP_PHOENIX  | CMD_NONE,     "What were you doing near the scene of the crime anyway?"      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_STOPMUS,  "Uh..."      },
{   EV_NONE,    45,     PP_PHOENIX  | CMD_NONE,     "Well?"      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_NONE,     "I-I was practicing for the Equestrian 500."      },
{   EV_NONE,    51,     PP_RAINBOW  | CMD_LOCKSFX,  "Yep, that's what I was doing... practicing for the big race!"      },
{   EV_NONE,    52,     PP_PHOENIX  | CMD_NONE,     "(Psyche-locks... you're a bad liar. Even without this thing I can tell that you are hiding something from me.)"      },
{   EV_NONE,    38,     PP_PHOENIX  | CMD_NONE,     "Look Rainbow Dash, if I am going to defend you, you're going to need to be honest with me..."      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_NONE,     "I told you a dozen times already, I didn't do it!"      },
{   EV_NONE,    35,     PP_PHOENIX  | CMD_NONE,     "I am not saying you did it! I'm just wondering what you were doing near the scene of the crime."      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_NONE,     "Um... well... uh-oh...!"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "Looks like visiting hours are over!"      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "Catch ya later, Nix!"      },
{   EV_NONE,    34,     PP_PHOENIX  | CMD_NONE,     "Hey! No they aren't! There are still five minutes left!"      },
{   EV_NONE,    34,     PP_PHOENIX  | CMD_NONE,     "She's gone..."      },
{   EV_NONE,    34,     PP_PHOENIX  | CMD_NONE,     "Oh well, I probably need more information to pursue that any further anyway. As long as she didn't do it that is all I need to know for now."      },
    
{   4,          34,     PP_NONE     | CMD_ENDSTORY, ""  }   // go to location 4

};
#endif

#ifdef LOCATION_IS_4
//      story                                    //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                       //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   EV_NONE,    17,     PP_NONE     | CMD_NONE  ,   "Ponyville June 9th, 10:30PM"   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_CHIMESFX, "Phoenix! How did it go?"   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE  ,   "I have decided to represent Rainbow Dash."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE  ,   "Oh, thank you so much Mr. Wright!"   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_NONE  ,   "She said she didn't do it and I can't turn my back on the innocent, or let them be punished for something they didn't do."   },
{   EV_NONE,    21,     PP_TWILIGHT | CMD_NONE  ,   "You share a very similar trait to Rainbow Dash, Mr. Wright."   },
{   EV_NONE,    21,     PP_PHOENIX  | CMD_NONE  ,   "I do? Am I really that obnoxious?"   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE  ,   "No, you are very loyal."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE  ,   "She probably may not have looked it, but Rainbow Dash is probably really scared about what is going to happen to her."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE  ,   "So she needs all the support she can get right now."   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE  ,   "Now that you mention it, she did seem awfully chipper for someone who is the prime suspect for murder."   },
{   EV_NONE,    33,     PP_TWILIGHT | CMD_NONE  ,   "I can't imagine what it must be like..."   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE  ,   "I have been in that place before."   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_NONE  ,   "\"That place\"?"   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_CHIMESFX, "What do you mean by that, Phoenix?"   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_MUSRECALL,"I have been on trial for crimes I didn't commit, I know how she probably feels."   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_BLACK ,   "You have?"   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_BLACK ,   "It felt dark and lonely having nobody to turn to."   },
{   EV_NONE,    53,     PP_PHOENIX  | CMD_NONE  ,   "Feeling as if the whole world was against me and nobody could help..."   },
{   EV_NONE,    54,     PP_PHOENIX  | CMD_NONE  ,   "Once when I was just a kid, my whole class accused me of stealing and we had this stupid \"Class Trial\"."   },
{   EV_NONE,    54,     PP_PHOENIX  | CMD_NONE  ,   "The other time was a little more serious..."   },
{   EV_NONE,    55,     PP_PHOENIX  | CMD_NONE  ,   "I was framed for murder by someone who I thought cared for me."   },
{   EV_NONE,    55,     PP_PHOENIX  | CMD_STOPMUS,  "I learned the hard way appearances can be deceiving..."   },
{   EV_NONE,    56,     PP_PHOENIX  | CMD_MUSSISTER,"But I was lucky to have friends who pulled me out of that darkness."   },
{   EV_NONE,    56,     PP_PHOENIX  | CMD_NONE  ,   "It really touched me..."   },
{   EV_NONE,    56,     PP_PHOENIX  | CMD_NONE  ,   "It's what made me decide to become a defense attorney."   },
{   EV_NONE,    57,     PP_PHOENIX  | CMD_NONE  ,   "A defense attorney is someone who is there for you when times are grim."   },
{   EV_NONE,    57,     PP_PHOENIX  | CMD_NONE  ,   "Showing you have someone who trusts and believes in you - that you are not alone."   },
{   EV_NONE,    58,     PP_PHOENIX  | CMD_NONE  ,   "Smiling to the very end no matter how bad things may get."   },
{   EV_NONE,    59,     PP_TWILIGHT | CMD_NONE,  "Mr. Wright... You know, I was going to study some law and justice books and be Rainbow Dash's defense attorney myself if you declined."   },
{   EV_NONE,    21,     PP_TWILIGHT | CMD_NONE  ,   "But I see now that there is some knowledge out there even books can't teach."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE  ,   "It was no mistake choosing you to be Rainbow Dash's lawyer!"   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_STOPMUS,  "(\"Choose\"? Didn't you bring me here by accident?)"   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_NONE  ,   "So did you learn anything else from Rainbow Dash?"   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE  ,   "Yes, she said the crime scene was in the clearing of the \"Everfree Forest\" near \"Butshersty's\" house."   },
{   EV_NONE,    18,     PP_TWILIGHT | CMD_NONE  ,   "\"Butshersty\"?"   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE  ,   "Oh-oh! You mean Fluttershy!"   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_NONE  ,   "Do you know the way?"   },
{   EV_NONE,    21,     PP_TWILIGHT | CMD_NONE  ,   "Sure do!"   },
{   EV_NONE,    21,     PP_PHOENIX  | CMD_NONE  ,   "Let's go then."   },

{   5,          34,     PP_NONE     | CMD_ENDSTORY, ""  }   // go to location 5

};
#endif

#ifdef LOCATION_IS_5
//      story                                        //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                           //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   EV_NONE,    60,     PP_NONE         | CMD_NONE,     "Fluttershy's Cottage June 9th, 11:16PM"    },
{   EV_NONE,    61,     PP_TWILIGHT     | CMD_NONE,     "Phoenix, we should stop here."    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "Why's that?"    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "Oh! This must be Flutterscotch's house. We can probably question her to see if she saw anything last night."    },
{   EV_NONE,    61,     PP_TWILIGHT     | CMD_NONE,     "Her name is Fluttershy..."    },
{   EV_NONE,    61,     PP_TWILIGHT     | CMD_NONE,     "And those were my thoughts exactly."    },
{   EV_NONE,    62,     PP_UNKNOWN      | CMD_CHIMESFX, "*Gasp*"    },
{PP_FLUTTERSHY, 63,     PP_TWILIGHT     | CMD_ADDEV,    "Hey Fluttershy, meet Mr. Wright! He's Rainbow Dash's lawyer."    },
{   EV_NONE,    64,     PP_PHOENIX      | CMD_NONE,     "Hello there, nice to meet you."    },
{   EV_NONE,    65,     PP_FLUTTERSHY   | CMD_NONE,     "..."    },
{   EV_NONE,    65,     PP_PHOENIX      | CMD_NONE,     "So Ponyville is a really nice place, huh?"    },
{   EV_NONE,    65,     PP_PHOENIX      | CMD_NONE,     "(Talk about quiet, certainly lives up to her name.)"    },
{   EV_NONE,    66,     PP_FLUTTERSHY   | CMD_NONE,     "*Whisper*"    },
{   EV_NONE,    67,     PP_TWILIGHT     | CMD_NONE,     "Oh... Oh... Okay..."    },
{   EV_NONE,    67,     PP_PHOENIX      | CMD_NONE,     "W-what's she saying?"    },
{   EV_NONE,    67,     PP_TWILIGHT     | CMD_NONE,     "She is saying suits and ties intimidate her."    },
{   EV_NONE,    65,     PP_PHOENIX      | CMD_NONE,     "(Trust me, they scare me too.)"    },
{   EV_NONE,    61,     PP_TWILIGHT     | CMD_NONE,     "And..."    },
{   EV_NONE,    67,     PP_TWILIGHT     | CMD_NONE,     "Uh... Nevermind."    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "Tell me! She can rest assured, she has nothing to fear."    },
{   EV_NONE,    61,     PP_TWILIGHT     | CMD_NONE,     "Well..."    },
{   EV_NONE,    68,     PP_TWILIGHT     | CMD_NONE,     "She says she is afraid if she gets too close to that pointy... \"beast\" on your head, it might... poke her eye out."    },
{   EV_NONE,    68,     PP_PHOENIX      | CMD_FALLSFX,  "(Seriously, the hair jokes are getting old!)"    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "So she isn't going to speak to me?"    },
{   EV_NONE,    67,     PP_TWILIGHT     | CMD_NONE,     "Sorry, she is kind of shy."    },
{   EV_NONE,    65,     PP_PHOENIX      | CMD_NONE,     "No kidding..."    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "Let's go to the crime scene then. We're not going to get any info here if she is refusing to speak to me."    },
{   EV_NONE,    69,     PP_TWILIGHT     | CMD_NONE,     "The crime scene is right over here, Phoenix."    },
{   EV_NONE,    69,     PP_PHOENIX      | CMD_NONE,     "Okay."    },
{   EV_NONE,    70,     PP_PHOENIX      | CMD_CHIMESFX, "Huh?"    },
{   EV_NONE,    70,     PP_FLUTTERSHY   | CMD_NONE,     "A... \"Phoenix\"?"    },
{   EV_NONE,    70,     PP_PHOENIX      | CMD_NONE,     "Y-yeah, that is my name."    },
{   EV_NONE,    71,     PP_FLUTTERSHY   | CMD_MUSPEARLY,"Oh my, I am so sorry, I didn't know!"    },
{   EV_NONE,    71,     PP_PHOENIX      | CMD_NONE,     "Know what?"    },
{   EV_NONE,    72,     PP_FLUTTERSHY   | CMD_NONE,     "That you were a phoenix. I have only seen one other phoenix in my life."    },
{   EV_NONE,    73,     PP_FLUTTERSHY   | CMD_NONE,     "This is so great, you can speak."    },
{   EV_NONE,    73,     PP_PHOENIX      | CMD_NONE,     "Come again?"    },
{   EV_NONE,    73,     PP_FLUTTERSHY   | CMD_NONE,     "No wonder you look so homely and sick. Don't worry though, soon you will rise from your ashes into a beautiful bird of fire!"    },
{   EV_NONE,    72,     PP_PHOENIX      | CMD_NONE,     "(Did I just get insulted?)"    },
{   EV_NONE,    72,     PP_PHOENIX      | CMD_NONE,     "But I'm not a..."    },
{   EV_NONE,    74,     PP_TWILIGHT     | CMD_NONE,     "Phoenix!"    },
{   EV_NONE,    74,     PP_PHOENIX      | CMD_NONE,     "What?"    },
{   EV_NONE,    61,     PP_TWILIGHT     | CMD_NONE,     "She is speaking to you, just go along with it."    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "Oh, that's right..."    },
{   EV_NONE,    72,     PP_PHOENIX      | CMD_NONE,     "Yup! I'm a Phoenix, Firefly."    },
{   EV_NONE,    75,     PP_FLUTTERSHY   | CMD_NONE,     "My name is Fluttershy, Mr. Phoenix."    },
{   EV_NONE,    71,     PP_FLUTTERSHY   | CMD_NONE,     "But you can call me whatever you want..."    },
{   EV_NONE,    71,     PP_PHOENIX      | CMD_NONE,     "Right..."    },
{   EV_NONE,    71,     PP_PHOENIX      | CMD_NONE,     "So Fluttershy, I take it you know about your friend Rainbow Dash?"    },
{   EV_NONE,    70,     PP_FLUTTERSHY   | CMD_NONE,     "Yes I do..."    },
{   EV_NONE,    65,     PP_FLUTTERSHY   | CMD_NONE,     "Oh, poor Rainbow Dash, she must be so scared right now."    },
{   EV_NONE,    65,     PP_PHOENIX      | CMD_NONE,     "That's why I need your help."    },
{   EV_NONE,    70,     PP_FLUTTERSHY   | CMD_NONE,     "How can I help, Mr. Phoenix?"    },

{   EV_T_FSEE,  70,     PP_FLUTTERSHY  | CMD_ADDPROMPT, "Did you see anything?"    },
{   EV_NONE,    70,     PP_FLUTTERSHY  | CMD_SELPROMPT, ""  },

{   EV_T_FSEE,  70,     PP_PHOENIX      | CMD_NONE,     "You live right near the crime scene."    },
{   EV_NONE,    70,     PP_PHOENIX      | CMD_NONE,     "Did you see anything suspicious last night?"    },
{   EV_NONE,    75,     PP_FLUTTERSHY   | CMD_NONE,     "Why, yes, I did."    },
{   EV_NONE,    75,     PP_PHOENIX      | CMD_NONE,     "That's great! Tell me everything you know!"    },
{   EV_NONE,    70,     PP_FLUTTERSHY   | CMD_NONE,     "Well, I saw-"    },
{   EV_NONE,    65,     PP_FLUTTERSHY   | CMD_CHIMESFX, "Oops... Oh, I'm so sorry Mr. Phoenix..."    },
{   EV_NONE,    65,     PP_FLUTTERSHY   | CMD_NONE,     "The other ponies told me not to say a word to anyone about last night until I was on the stand."    },
{   EV_NONE,    65,     PP_FLUTTERSHY   | CMD_NONE,     "Whatever that means..."    },
{   EV_NONE,    65,     PP_PHOENIX      | CMD_FLASH,    "Wait a minute, you're a witness!?"    },
{   EV_NONE,    75,     PP_FLUTTERSHY   | CMD_NONE,     "I don't even know what that is Mr. Phoenix."    },
{   EV_NONE,    75,     PP_PHOENIX      | CMD_CLRPROMPT, "(You sure your name isn't \"FlutterNaive\"?)"    },

{   EV_T_FBEG,  70,     PP_FLUTTERSHY  | CMD_ADDPROMPT, "Please tell me what you saw!"    },
{   EV_T_FWORK, 70,     PP_FLUTTERSHY  | CMD_ADDPROMPT, "What do you do for work?"    },
{   EV_NONE,    70,     PP_FLUTTERSHY  | CMD_SELPROMPT, ""  },

{   EV_T_FBEG,  70,     PP_PHOENIX      | CMD_NONE,     "It's okay, it'll be our little secret. Just tell me what you saw."    },
{   EV_NONE,    61,     PP_TWILIGHT     | CMD_NONE,     "Come on Fluttershy. We need to know."    },
{   EV_NONE,    65,     PP_FLUTTERSHY   | CMD_NONE,     "I'm sorry Twilight, but I don't want those ponies to be mad at me..."    },
{   EV_NONE,    65,     PP_PHOENIX      | CMD_NONE,     "*sigh* Why can this never be easy?"    },

{   EV_NONE,    70,     PP_FLUTTERSHY  | CMD_SELPROMPT, ""  },

{   EV_T_FWORK, 65,     PP_PHOENIX      | CMD_NONE,     "So what is it you do, Fluttershy?"    },
{   EV_NONE,    76,     PP_FLUTTERSHY   | CMD_NONE,     "I take care of my little animal friends, of course."    },
{   EV_NONE,    72,     PP_PHOENIX      | CMD_NONE,     "So you're good with animals, huh?"    },
{   EV_NONE,    72,     PP_PHOENIX      | CMD_NONE,     "(I don't find it surprising, since she is an animal herself.)"    },
{   EV_NONE,    71,     PP_FLUTTERSHY   | CMD_NONE,     "Why yes, I can introduce you to them if you want..."    },
{   EV_NONE,    71,     PP_PHOENIX      | CMD_NONE,     "That is alright, we're kind of busy."    },
{   EV_NONE,    65,     PP_FLUTTERSHY   | CMD_NONE,     "Oh my! I'm so sorry, I didn't mean to bother you..."    },
{   EV_NONE,    65,     PP_PHOENIX      | CMD_NONE,     "It's all right... no need to apologize."    },
{   EV_NONE,    61,     PP_TWILIGHT     | CMD_NONE,     "We have to get going, Fluttershy. We'll talk to you later."    },
{   EV_NONE,    72,     PP_FLUTTERSHY   | CMD_NONE,     "Alright, bye Twilight! Bye Mr. Phoenix!"    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "At least I got her trust, it will be a little easier inevitably cross examining her when we are in court."    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "Speaking of that... when is the trial, anyway?"    },
{   EV_NONE,    67,     PP_TWILIGHT     | CMD_NONE,     "Tomorrow morning."    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_STOPMUS,  "Oh. Tomorrow morning..."    },
{   EV_NONE,    77,     PP_PHOENIX      | CMD_FLASH,    "TOMORROW MORNING!?"    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "As in \"tomorrow\" tomorrow!?"    },
{   EV_NONE,    67,     PP_TWILIGHT     | CMD_NONE,     "Yup. \"Tomorrow\" tomorrow."    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "So I have only a few hours to gather evidence and present a case!?"    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "(Phoenix, what have you gotten yourself into...?)"    },
{   EV_NONE,    77,     PP_TWILIGHT     | CMD_NONE,     "Oh my gosh! I totally lost track of time!"    },
{   EV_NONE,    78,     PP_TWILIGHT     | CMD_NONE,     "I have been trying to get a suitable lawyer all day long, I was just going to give up after you."    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "Give up after me? You mean I'm not the only lawyer you have spoken with today?"    },
{   EV_NONE,    79,     PP_TWILIGHT     | CMD_NONE,     "That is correct. They all declined though... as soon as murder was brought up."    },
{   EV_NONE,    79,     PP_PHOENIX      | CMD_NONE,     "Don't worry, murder cases aren't anything new to me. I have a lot of experience with them. Rainbow Dash couldn't be in any better hands."    },
{   EV_NONE,    63,     PP_TWILIGHT     | CMD_NONE,     "Thank you again for accepting this, Phoenix!"    },
{   EV_NONE,    61,     PP_TWILIGHT     | CMD_NONE,     "But we better hurry to the crime scene though."    },
{   EV_NONE,    61,     PP_PHOENIX      | CMD_NONE,     "Right!"    },

{   6,          61,     PP_NONE         | CMD_ENDSTORY, ""  }   // go to location 6

};
#endif

#ifdef LOCATION_IS_6
//      story                                        //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                           //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   EV_NONE,    80, PP_NONE     | CMD_BLACK,            "Everfree Forest. June 9th, 11:30PM"    },
{   EV_NONE,    80, PP_TWILIGHT | CMD_BLACK,            "Welcome to the Everfree Forest, Mr. Wright."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_BLACK,            "Kind of spooky..."    },
{   EV_NONE,    80, PP_TWILIGHT | CMD_BLACK,            "There are many deadly creatures in the Everfree Forest."    },
{   EV_NONE,    80, PP_TWILIGHT | CMD_BLACK,            "Everypony tends to avoid entering here because of that."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_BLACK,            "D-deadly creatures?"    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_BLACK,            "A-ah! HELP! Something just touched my hand!"    },
{   EV_NONE,    80, PP_TWILIGHT | CMD_BLACK,            "That was just my tail. Don't worry Phoenix, we aren't that deep. Most of the menacing things live much further in."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_BLACK,            "Oh-oh okay."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_BLACK,            "(Come on! Don't be such a chicken, Phoenix!)"    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_BLACK,            "Look, there is a clearing... this must be it..."    },
{   EV_NONE,    80, PP_TWILIGHT | CMD_BLACK,            "Hard to believe somepony died here..."    },

{   EV_T_INVEST,80, PP_PHOENIX  | CMD_ADDPROMPT,        "Where are the investigators?"    },
{   EV_T_DARK,  80, PP_PHOENIX  | CMD_ADDPROMPT,        "It's too dark!"    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_SELPROMPT,        ""  },

{   EV_T_INVEST,80, PP_PHOENIX  | CMD_BLACK,            "Aren't there any crime scene investigators?"    },
{   EV_NONE,    80, PP_TWILIGHT | CMD_BLACK,            "They're probably all finished up."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_BLACK,            "Bonus for me, I guess..."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_BLACK,            "Let's get down to work then!"    },

{   EV_NONE,    80, PP_PHOENIX  | CMD_SELPROMPT,        ""  },

{   EV_T_DARK,  80, PP_PHOENIX  | CMD_BLACK,            "But there is a little problem..."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_BLACK,            "It's way too dark here. I can hardly see anything and I don't have a flashlight."    },
{   EV_NONE,    80, PP_TWILIGHT | CMD_BLACK,            "Let me take care of that."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_BLACK,            "(It's that horn again. It's lighting up like a candle. That must be really handy.)"    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_MAGICSFX,         "Good work, Twilight."    },
{   EV_NONE,    81, PP_TWILIGHT | CMD_MUSMIDDLE,        "Alright! Let's find some clues!"    },
{   EV_NONE,    81, PP_PHOENIX  | CMD_NONE,             "(She seems really eager to start this up.)"    },

// first screen investigation
{   EV_NONE  ,      9801,           PP_NONE     | CMD_NONE,         "BEGIN INVESTIGATION - use arrows to move box, press enter to inspect area. Press < or > to shift view."    },
{EV_T_IN1_SC1,      9801,           PP_NONE     | CMD_NONE,         ""    },
{   EV_NONE,        EV_T_IRIGHTOK,  PP_PHOENIX  | CMD_INVESTIGATE,  ""    },
{   EV_I_4,         EV_T_I11_4,     PP_PHOENIX  | CMD_JUMPIFSHOW,   ""    },
{   EV_I_5,         EV_T_I11_5,     PP_PHOENIX  | CMD_JUMPIFSHOW,   ""    },
{EV_I_SEARCH_RIGHT, EV_T_IN1_SC2,   PP_PHOENIX  | CMD_JUMPIFSHOW,   ""    },
{EV_T_I11_NOTHING,  9801,           PP_PHOENIX  | CMD_JUMP,         "" }, 

// first screen nothing here
{EV_T_I11_NOTHING,  9801,           PP_PHOENIX  | CMD_NONE,        "Nothing interesting here..." }, 
{EV_PHOTO1,         EV_T_IN1_SC1,   PP_PHOENIX  | CMD_JUMPIFNOEV,  "" }, 
{EV_BURNT,          EV_T_IN1_SC1,   PP_PHOENIX  | CMD_JUMPIFNOEV,  "" }, 
{EV_NONE,           9801,           PP_PHOENIX  | CMD_NONE,        "I should check the rest of the clearing..." }, 
{EV_T_IN1_SC1,      9801,           PP_PHOENIX  | CMD_JUMP,        "" }, 

{   EV_T_I11_5, 81, PP_PHOENIX  | CMD_NONE,             "Hey! Look at this!"    },
{   EV_NONE,    80, PP_TWILIGHT | CMD_NONE,             "Why is there tape all over the grass?"    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_NONE,             "If it's anything like in my world, this is probably where they found Ace Swift's body."    },
{   EV_NONE,    82, PP_TWILIGHT | CMD_NONE,             "Ugh... I think I'm going to be sick..."    },
{   EV_NONE,    82, PP_PHOENIX  | CMD_NONE,             "(And all that eagerness seemed to go away in one fell swoop.)"    },
{   EV_NONE,    80, PP_TWILIGHT | CMD_NONE,             "Wait, the victim was Ace Swift?"    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_NONE,             "That is what Rainbow Dash told me..."    },
{   EV_NONE,    83, PP_TWILIGHT | CMD_NONE,             "Ace Swift, hmm..."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_NONE,             "It's strange, though..."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_NONE,             "There's no blood at all."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_NONE,             "Uh... ponies can bleed, right?"    },
{   EV_NONE,    83, PP_TWILIGHT | CMD_NONE,             "Of course they can!"    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_NONE,             "It's just really strange there is a murder, but not a drop of blood in sight."    },
{   EV_NONE,    83, PP_TWILIGHT | CMD_NONE,             "This grass is odd, too. It's all black..."    },
{   EV_NONE,    83, PP_PHOENIX  | CMD_NONE,             "You're right. It is all charred and burned like there was a small fire around the body."    },
{   EV_PHOTO1,  84, PP_NONE     | CMD_ADDEV,            "Photo#1 - Charred and blackened grass around body."    },
{   EV_NONE,    81, PP_TWILIGHT | CMD_NONE,             "\"Steel Samurai\"? That sure is an interesting looking camera, Phoenix."    },
{   EV_NONE,    81, PP_PHOENIX  | CMD_NONE,             "It's not mine, it belongs to a friend."    },
{   EV_NONE,    81, PP_PHOENIX  | CMD_NONE,             "(Hey! Maybe I should tell Twilight about \"The Steel Samuari\". Amazing how a kids' show got so popular outside its targeted demographic.)"    },
// check if that was the last piece
{EV_PHOTO1, EV_T_IN1_SC1, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_BURNT,  EV_T_IN1_SC1, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_PHOTO2, EV_T_IN1_SC1, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_FEATHER,EV_T_IN1_SC1,PP_PHOENIX  | CMD_JUMPIFNOEV,  "" },
{EV_T_IN1_DONE, 9803,    PP_PHOENIX  | CMD_JUMP,        "" },

{   EV_T_I11_4, 80, PP_TWILIGHT | CMD_NONE,             "Hey, look there. That thing on the ground next to where the body was."    },
{   EV_NONE,    85, PP_TWILIGHT | CMD_NONE,             ""    },
{   EV_NONE,    85, PP_PHOENIX  | CMD_NONE,             "It's a... what the heck is this thing!?"    },
{   EV_NONE,    85, PP_TWILIGHT | CMD_NONE,             "I don't have any idea."    },
{   EV_NONE,    85, PP_PHOENIX  | CMD_NONE,             "Whatever it was, it's totally burnt to a crisp."    },
{   EV_NONE,    80, PP_TWILIGHT | CMD_NONE,             "Just like the grass."    },
{   EV_NONE,    80, PP_PHOENIX  | CMD_NONE,             "This may be important evidence."    },
{   EV_BURNT,   86, PP_NONE     | CMD_ADDEV,            "Burnt Object: A metal object that was severely burned by something. It is unidentifiable now."    },
// check if that was the last piece
{EV_PHOTO1, EV_T_IN1_SC1, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_BURNT,  EV_T_IN1_SC1, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_PHOTO2, EV_T_IN1_SC1, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_FEATHER,EV_T_IN1_SC1,PP_PHOENIX  | CMD_JUMPIFNOEV,  "" },
{EV_T_IN1_DONE, 9803,    PP_PHOENIX  | CMD_JUMP,        "" },

// second screen investigation
{EV_T_IN1_SC2,      9802,           PP_NONE     | CMD_NONE,         ""    },
{   EV_NONE,        EV_T_IBOTHOK,   PP_PHOENIX  | CMD_INVESTIGATE,  ""    },
{   EV_I_4,         EV_T_I12_4,     PP_PHOENIX  | CMD_JUMPIFSHOW,   ""    },
{   EV_I_5,         EV_T_I12_4,     PP_PHOENIX  | CMD_JUMPIFSHOW,   ""    },    // allow 4 or 5
{EV_I_SEARCH_RIGHT, EV_T_IN1_SC3,   PP_PHOENIX  | CMD_JUMPIFSHOW,   ""    },
{EV_I_SEARCH_LEFT,  EV_T_IN1_SC1,   PP_PHOENIX  | CMD_JUMPIFSHOW,   ""    },
{EV_T_I12_NOTHING,  9802,           PP_PHOENIX  | CMD_JUMP,         "" }, 

// second screen nothing here
{EV_T_I12_NOTHING,  9802,           PP_PHOENIX  | CMD_NONE,        "Nothing interesting here..." }, 
{EV_PHOTO2,         EV_T_IN1_SC2,   PP_PHOENIX  | CMD_JUMPIFNOEV,  "" }, 
{EV_NONE,           9802,           PP_PHOENIX  | CMD_NONE,        "I should check the rest of the clearing..." }, 
{EV_T_IN1_SC2,      9802,           PP_PHOENIX  | CMD_JUMP,        "" }, 

{EV_T_I12_4,    80, PP_PHOENIX  | CMD_NONE,             "Let's look at that dirt landscape over there."    },
{   EV_NONE,    81, PP_TWILIGHT | CMD_NONE,             "Sure thing!"    },
{   EV_NONE,    87, PP_PHOENIX  | CMD_NONE,             "What's this?"    },
{   EV_NONE,    88, PP_TWILIGHT | CMD_NONE,             "There is an imprint of something in the dirt, something long..."    },
{   EV_NONE,    88, PP_PHOENIX  | CMD_NONE,             "That isn't what I find odd..."    },
{   EV_NONE,    89, PP_TWILIGHT | CMD_NONE,             "What do you mean?"    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "Look next to it, someone obviously disturbed the dirt here."    },
{   EV_NONE,    88, PP_TWILIGHT | CMD_NONE,             "Now that you mention it... this doesn't look natural at all. It looks like somepony was kicking the dirt around in this area."    },
{  EV_PHOTO2,   90, PP_NONE     | CMD_ADDEV,            "Photo#2: An imprint of what seems to be something long. Next to it some markings indicating someone had scuffled the dirt around."    },

// check if that was the last piece
{EV_PHOTO1, EV_T_IN1_SC2, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_BURNT,  EV_T_IN1_SC2, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_PHOTO2, EV_T_IN1_SC2, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_FEATHER,EV_T_IN1_SC2,PP_PHOENIX  | CMD_JUMPIFNOEV,  "" },
{EV_T_IN1_DONE, 9803,    PP_PHOENIX  | CMD_JUMP,        "" },

// Scene 3 sets a flag to skip the introductory text
{EV_T_IN1_SC3,  89, PP_PHOENIX  | CMD_NONE,             ""    },
{EV_I_IN1FLAG1, EV_T_IN1_SC3b, PP_PHOENIX  | CMD_JUMPIFEV, "" },

{EV_I_IN1FLAG1, 89, PP_PHOENIX  | CMD_ADDEV,            "See anything else suspicious?"    },
{   EV_NONE,    89, PP_TWILIGHT | CMD_NONE,             "Look at that tree way over there at the other end of the crime scene."    },
{   EV_NONE,    91, PP_PHOENIX  | CMD_NONE,             "It's knocked down..."    },
{   EV_NONE,    91, PP_TWILIGHT | CMD_NONE,             "But look at the trunk. It suffers from the same burning as the grass and that object."    },
{   EV_NONE,    91, PP_PHOENIX  | CMD_NONE,             "Can ponies breathe fire or something?"    },
{   EV_NONE,    92, PP_TWILIGHT | CMD_NONE,             "No Phoenix. Dragons do that, not ponies..."    },
{   EV_NONE,    91, PP_PHOENIX  | CMD_NONE,             "Heh! Maybe a dragon really did do all this."    },
{   EV_NONE,    92, PP_TWILIGHT | CMD_NONE,             "That isn't possible. Spike is the only dragon in Ponyville and he was with me all night."    },
{   EV_NONE,    91, PP_PHOENIX  | CMD_NONE,             "Spike..."    },
{   EV_NONE,    91, PP_PHOENIX  | CMD_NONE,             "That is your assistant you told me about..."    },
{   EV_NONE,    91, PP_PHOENIX  | CMD_NONE,             "Wait, he's a dragon!? There really are dragons here!?"    },
{   EV_NONE,    92, PP_TWILIGHT | CMD_NONE,             "Why, yes..."    },
{   EV_NONE,    91, PP_PHOENIX  | CMD_NONE,             "You said you wanted to introduce me to him..."    },
{   EV_NONE,    91, PP_PHOENIX  | CMD_NONE,             "I-it's quite alright. Y-you don't need to, he's p-probably a really nice guy."    },
{   EV_NONE,    93, PP_TWILIGHT | CMD_NONE,             "Don't be so shy, Spike loves company!"    },
{   EV_NONE,    93, PP_PHOENIX  | CMD_NONE,             "(gulp)"    },
{   EV_NONE,    93, PP_PHOENIX  | CMD_NONE,             "(I really hope that doesn't have a double meaning to it!)"    },

// third screen investigation
{EV_T_IN1_SC3b,     9803,           PP_PHOENIX  | CMD_NONE,         ""    },
{   EV_NONE,        EV_T_ILEFTOK,   PP_PHOENIX  | CMD_INVESTIGATE,  ""    },
{   EV_I_7,         EV_T_I13_7,     PP_PHOENIX  | CMD_JUMPIFSHOW,   ""    },
{EV_I_SEARCH_LEFT,  EV_T_IN1_SC2,   PP_PHOENIX  | CMD_JUMPIFSHOW,   ""    },
{EV_T_I13_NOTHING,  9803,           PP_PHOENIX  | CMD_JUMP,         ""    }, 

// third screen nothing here
{EV_T_I13_NOTHING,  9803,           PP_PHOENIX  | CMD_NONE,        "Nothing interesting here..." }, 
{EV_FEATHER,        EV_T_IN1_SC3b,  PP_PHOENIX  | CMD_JUMPIFNOEV,  "" }, 
{EV_NONE,           9803,           PP_PHOENIX  | CMD_NONE,        "I should check the rest of the clearing..." }, 
{EV_T_IN1_SC3b,     9803,           PP_PHOENIX  | CMD_JUMP,        "" }, 

{ EV_T_I13_7,   94, PP_TWILIGHT | CMD_NONE,             "Oh Phoenix! Look on that branch there, on that tree behind the fallen one."    },
{   EV_NONE,    94, PP_PHOENIX  | CMD_NONE,             "There is something stuck on it. I'll climb up and get it..."    },
{   EV_NONE,    93, PP_TWILIGHT | CMD_NONE,             "No need, Mr. Wright."    },
{   EV_NONE,    93, PP_PHOENIX  | CMD_NONE,             "(Or you could just float it down...)"    },
{   EV_NONE,    95, PP_PHOENIX  | CMD_NONE,             "It's a brown... feather..."    },
{   EV_NONE,    95, PP_PHOENIX  | CMD_NONE,             "Well that was pointless. Probably from a bird."    },
{   EV_NONE,    89, PP_TWILIGHT | CMD_NONE,             "No, it can't be. No bird in Ponyville is this big."    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "I know, maybe it is the victim's. He was a pegasus, right? Maybe it is from his wings."    },
{   EV_NONE,    89, PP_TWILIGHT | CMD_NONE,             "Nope, this feather doesn't belong to a pony, either. Too big."    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "Then we should keep it."    },
{   EV_FEATHER, 96, PP_NONE     | CMD_ADDEV,            "Brown feather: A suspicious brown feather that doesn't belong to a bird or a pony."    },

// check if that was the last piece
{EV_PHOTO1, EV_T_IN1_SC3b, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_BURNT,  EV_T_IN1_SC3b, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_PHOTO2, EV_T_IN1_SC3b, PP_PHOENIX | CMD_JUMPIFNOEV,  "" }, 
{EV_FEATHER,EV_T_IN1_SC3b,PP_PHOENIX  | CMD_JUMPIFNOEV,  "" },
// fall through 

{ EV_T_IN1_DONE,89, PP_PHOENIX  | CMD_NONE,             ""                     },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "How do you do that, Twilight?"    },
{   EV_NONE,    88, PP_TWILIGHT | CMD_NONE,             "Do what, Phoenix?"    },
{   EV_NONE,    88, PP_PHOENIX  | CMD_NONE,             "I've seen you levitating things with that horn of yours."    },
{   EV_NONE,    88, PP_PHOENIX  | CMD_NONE,             "Not to mention you are lighting this whole area with it at this very moment."    },
{   EV_NONE,    94, PP_TWILIGHT | CMD_NONE,             "It's magic. Levitation and illumination are two of the basic spells a unicorn can learn."    },
{   EV_NONE,    89, PP_TWILIGHT | CMD_NONE,             "Why do you ask? Is there no magic in your world?"    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_CLRPROMPT,        "No, there isn't..."    },

{ EV_T_ISMAGIC, 89, PP_PHOENIX  | CMD_ADDPROMPT,        "Well, some magic..."    },
{ EV_T_NODECIS, 89, PP_PHOENIX  | CMD_ADDPROMPT,        "We've nothing decisive..."    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_SELPROMPT,        ""  },

{ EV_T_ISMAGIC, 89, PP_PHOENIX  | CMD_NONE,             "Actually, you could say there is..."    },
{   EV_NONE,    93, PP_TWILIGHT | CMD_NONE,             "Please do tell. You see, magic is sort of my bread and butter, I want to learn everything there is to know about it."    },
{   EV_NONE,    93, PP_PHOENIX  | CMD_NONE,             "Well, I have been able to speak to the dead via spirit channeling. That could be considered magic, I guess."    },
{   EV_NONE,    89, PP_TWILIGHT | CMD_NONE,             "Spirit channeling?"    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "It's when the spirit of someone who is departed possesses the body of the living."    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "I have used it to keep in touch with someone very dear to me."    },
{   EV_NONE,    88, PP_TWILIGHT | CMD_NONE,             "Oh, I get it..."    },
{   EV_NONE,    93, PP_TWILIGHT | CMD_NONE,             "Hey! Phoenix, can't you do it right now? We can get Ace Swift in your body and ask who killed him."    },
{   EV_NONE,    93, PP_PHOENIX  | CMD_NONE,             "Heh, sorry. I forgot to mention you have to be a high level spirit medium in order to perform the channeling technique."    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "My friend is the one who normally does it."    },
{   EV_NONE,    88, PP_TWILIGHT | CMD_NONE,             "I see..."    },
{   EV_NONE,    93, PP_TWILIGHT | CMD_NONE,             "Thanks for the information though. I'll definitely look into it more."    },

{   EV_NONE,    89, PP_PHOENIX  | CMD_SELPROMPT,        ""  },

{EV_T_NODECIS,  89, PP_PHOENIX  | CMD_NONE,             "Hmm... No decisive evidence yet. We still don't even know how this guy died."    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "Hey, Twilight. Do you know anything about him?"    },
{   EV_NONE,    89, PP_TWILIGHT | CMD_NONE,             "I know a bit of information about him."    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "All right, anything helps..."    },
{   EV_NONE,    89, PP_TWILIGHT | CMD_NONE,             "Well, Ace was an athlete who got extremely popular around Equestria by winning every event he's ever competed in."    },
{   PP_ACE2,    89, PP_PHOENIX  | CMD_REMOVEEV,         "He won EVERY single event he's ever competed in!?"    },
{   PP_ACE,     89, PP_TWILIGHT | CMD_ADDEV,            "Yeah, he was that good..."    },
{   EV_NONE,    89, PP_TWILIGHT | CMD_NONE,             "But with this streak of success he gained a few skeptics thinking that all his victories were a result of cheating and other dubious methods."    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "I'd probably think the same if I saw someone winning at everything they do."    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "*cough*"    },
{   EV_NONE,    89, PP_TWILIGHT | CMD_NONE,             "He was supposed to be competing in the Equestrian 500 and was the racer expected most likely to win."    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_STOPMUS,          "Rainbow Dash told me about that too. Unfortunately it sets up a motive for her..."    },
{   EV_NONE,    89, PP_TWILIGHT | CMD_NONE,             "What do you mean?"    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "Rainbow Dash said she was planning on flying in that race as well and she seemed really, well, determined on winning it."    },
{   EV_NONE,    94, PP_TWILIGHT | CMD_NONE,             "Yes, I remember her going around Ponyville bantering how she was going to be the one to take the gold."    },
{   EV_NONE,    89, PP_PHOENIX  | CMD_NONE,             "If she were to rub out the guy most likely to win, she would have more of a chance of winning the whole thing herself."    },
{   EV_NONE,    97, PP_TWILIGHT | CMD_MUSCORE,          "But she wouldn't do that!"    },
{   EV_NONE,    97, PP_PHOENIX  | CMD_NONE,             "Yes, yes I know. But we are going to have to prove otherwise to those who probably suspect that in court tomorrow."    },
{   EV_NONE,    98, PP_TWILIGHT | CMD_NONE,             "Sorry, I guess you're right."    },
{   EV_NONE,    98, PP_PHOENIX  | CMD_NONE,             "Can't say I'm really satisfied with the evidence we gathered but this looks like all we are going to find here..."    },
{   EV_NONE,    91, PP_TWILIGHT | CMD_NONE,             "The ponies investigating the crime scene must have taken all the important stuff."    },
{   EV_NONE,    91, PP_PHOENIX  | CMD_NONE,             "I'm sure we will see it presented in tomorrow's trial. In any case, we should go get some rest."    },
{   EV_NONE,    99, PP_TWILIGHT | CMD_NONE,             "What!? No studying or anything!?"    },
{   EV_NONE,    91, PP_PHOENIX  | CMD_NONE,             "Don't worry, I do it all the time. If I just keep my eyes set on truth, everything will be fine."    },
{   EV_NONE,    98, PP_TWILIGHT | CMD_NONE,             "I hope you really are the best defense attorney, Mr. Wright..."    },
{   EV_NONE,    98, PP_PHOENIX  | CMD_NONE,             "We have a big day ahead of us tomorrow."    },
{   EV_NONE,    94, PP_TWILIGHT | CMD_NONE,             "You can sleep at my house. I have an extra bed for you."    },
{   EV_NONE,    94, PP_PHOENIX  | CMD_NONE,             "(I still feel like I shouldn't be taking this case. I'm an outsider meddling in something that doesn't concern me at all...)"    },
{   EV_NONE,    94, PP_PHOENIX  | CMD_NONE,             "(But at the same time, I can't turn my back on someone who is being accused of a crime they didn't commit. That just goes against everything I stand for.)"    },
{   EV_NONE,    94, PP_PHOENIX  | CMD_NONE,             "(This whole thing is still really weird, talking ponies and all. But I said I would defend Rainbow Dash and that is what I am going to do.)"    },
{   EV_NONE,    94, PP_PHOENIX  | CMD_NONE,             "(I need to bring my A-game tomorrow, even with little evidence. I will find the truth and get Rainbow Dash acquitted of this murder.)"    },

{   10,         94,     PP_NONE         | CMD_ENDSTORY, ""  }   // go to location 10

};
#endif

#ifdef LOCATION_IS_10
//      story                                //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                   //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   EV_NONE,    100, PP_NONE     |  CMD_NONE,   "Ponyville District Court. June 10th, 9:45AM"   },
{   EV_NONE,    100, PP_PHOENIX  |CMD_MUSLOUNGE,"Coffee... need coffee..."   },
{   EV_NONE,    101, PP_TWILIGHT |  CMD_NONE,   "I told you Phoenix, we didn't have any..."   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "That bed was way too small. I hardly got any sleep last night."   },
{   EV_NONE,    101, PP_TWILIGHT |  CMD_NONE,   "It wasn't designed for someone as tall as you."   },
{   EV_NONE,    101, PP_PHOENIX  |  CMD_NONE,   "And I'm starving..."   },
{   EV_NONE,    101, PP_TWILIGHT |  CMD_NONE,   "Spike and I offered you breakfast but you wouldn't eat it!"   },
{   EV_NONE,    101, PP_PHOENIX  |  CMD_NONE,   "Sorry, but I don't eat hay!"   },
{   EV_NONE,    103, PP_TWILIGHT |  CMD_NONE,   "Stop whining!"   },
{   EV_NONE,    103, PP_PHOENIX  |  CMD_NONE,   "I am NOT whining, I'm complaining!"   },
{   EV_NONE,    103, PP_PHOENIX  |  CMD_NONE,   "Ugh, sorry Twilight, I'm just a bit nervous."   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "(I feel like such a rookie right now; I'm going to be the only human being in that courtroom.)"   },
{   EV_NONE,    102, PP_TWILIGHT |  CMD_NONE,   "I'm sorry too... the feeling's mutual."   },
{   EV_NONE,    104, PP_RAINBOW  |  CMD_CRASHSFX, "Hey!"   },
{   EV_NONE,    105, PP_PHOENIX  |  CMD_NONE,   "(Can't she just say \"Hello\" instead of blurting out \"Hey!\" like that?!)"   },
{   EV_NONE,    106, PP_RAINBOW  |  CMD_NONE,   "What's wrong with you two? I should be the one that's jumpy right now."   },
{   EV_NONE,    106, PP_PHOENIX  |  CMD_NONE,   "Oh... *ahem*... that's right..."   },
{   EV_NONE,    104, PP_RAINBOW  |  CMD_NONE,   "...So did you find any super awesome proof to clear my good name last night?"   },
{   EV_NONE,    107, PP_TWILIGHT |  CMD_NONE,   "Uh..."   },
{   EV_NONE,    104, PP_PHOENIX  |  CMD_NONE,   "I wouldn't exactly call it \"super awesome\"... we did get a tip off of who will be testifying as a witness today, so we got that on our side."   },
{   EV_NONE,    105, PP_RAINBOW  |  CMD_NONE,   "And who would that be?"   },
{   EV_NONE,    102, PP_TWILIGHT |  CMD_NONE,   "Fluttershy..."   },
{   EV_NONE,    108, PP_RAINBOW  |  CMD_NONE,   "WHAT?! Why is she testifying against me?! She better not say anything dumb!"   },
{   EV_NONE,    107, PP_TWILIGHT |  CMD_NONE,   "Calm down, Rainbow Dash. Fluttershy wouldn't do that..."   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "Twilight, do you know what the prosecuter is like?"   },
{   EV_NONE,    107, PP_TWILIGHT |  CMD_NONE,   "The prosecutor? I forgot to look into that..."   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "(Speaking of prosecutors... I wonder what Edgeworth would do if he were in my shoes right now...)"   },
{   EV_NONE,    109, PP_EDGEWORTH|  CMD_MUSMLP, "This is just like that one episode of the Steel Samurai where he meets the Pink Princess!"   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_STOPMUS,"(Doctor, I'd like the part of my brain responsible for that image lobotomized please...)"   },
{   EV_NONE,    107, PP_TWILIGHT |  CMD_NONE,   "Does it really matter what the prosecutor is like?"   },
{   EV_NONE,    107, PP_PHOENIX  |  CMD_NONE,   "Save a few, most of the prosecutors in my world are always stuck up, smug, and arrogant."   },
{   EV_NONE,    110, PP_TWILIGHT |  CMD_NONE,   "Don't worry, I don't think there is anypony in Equestria like that."   },
{   EV_NONE,    102, PP_UNKNOWN  |  CMD_NONE,   "HAHAHAHAHAHA!"   },
{   EV_NONE,    111, PP_TWILIGHT |  CMD_NONE,   "Oh... no..."   },
{   EV_NONE,    112, PP_UNKNOWN  |  CMD_MUSTROUPE, ""   },
{   EV_NONE,    113, PP_UNKNOWN  |  CMD_NONE,   "We meet again, Twilight SPARKLE."   },
{   EV_NONE,    113, PP_PHOENIX  |  CMD_NONE,   "Friend of yours?"   },
{   EV_NONE,    113, PP_PHOENIX  |  CMD_NONE,   "(What's with the get up?)"   },
{   EV_NONE,    114, PP_UNKNOWN  |  CMD_NONE,   "The GREAT and POWERFUL Trixie is no friend of Twilight Sparkle!"   },
{   EV_NONE,    101, PP_TWILIGHT |  CMD_NONE,   "What are you doing here, Trixie?"   },
{   EV_NONE,    114, PP_TRIXIE   |  CMD_NONE,   "Come one! Come all! The GREAT and POWERFUL Trixie will be displaying her PRODIGIOUS and CUNNING prowess as a Prosecutor in the courtroom today!"   },
{   EV_NONE,    111, PP_TWILIGHT |  CMD_NONE,   "You're the Prosecutor?!"   },
{   PP_TRIXIE,  112, PP_TRIXIE   |  CMD_ADDEV,  "Trixie is a mare of many talents. Does it really come as a surprise?"   },
{   EV_NONE,    112, PP_TRIXIE   |  CMD_NONE,   "As soon as Trixie caught wind of one of your pathetic little friends performing such a heinous act, Trixie jumped all over the opportunity to humiliate them as you had humiliated Trixie."   },
{   EV_NONE,    115, PP_RAINBOW  |  CMD_NONE,   "Who are you calling pathetic?!"   },
{   EV_NONE,    113, PP_TRIXIE   |  CMD_NONE,   "Oh? Are you mad?"   },
{   EV_NONE,    113, PP_TRIXIE   |  CMD_NONE,   "Don't worry, the GREAT and POWERFUL Trixie hears you're going to be having a nice long vacation on the sun -- that should get your mind off things!"   },
{   EV_NONE,    113, PP_TRIXIE   |  CMD_NONE,   "Bon voyage!"   },
{   EV_NONE,    108, PP_RAINBOW  |  CMD_NONE,   "Why you...!"   },
{   EV_NONE,    108, PP_PHOENIX  |  CMD_NONE,   "Rainbow Dash, don't let her rile you up; it could look bad for us..."   },
{   EV_NONE,    116, PP_TRIXIE   |  CMD_NONE,   "And just what in Celestia's name are YOU supposed to be?"   },
{   EV_NONE,    116, PP_PHOENIX  |  CMD_NONE,   "Me? I'm Rainbow's defense attorney... Phoenix Wright."   },
{   EV_NONE,    113, PP_TRIXIE   |  CMD_NONE,   "What?! You?! Hahahaha!"   },
{   EV_NONE,    113, PP_TRIXIE   |  CMD_NONE,   "This should be easy if Trixie's opponent is to be this hairless ape."   },
{   EV_NONE,    113, PP_TRIXIE   |  CMD_NONE,   "From what Trixie has gathered you are only here because \"Twilight Screw-up\" botched up a spell, HA!"   },
{   EV_NONE,    113, PP_TRIXIE   |  CMD_NONE,   "Trixie would never settle for a wretched-looking creature such as yourself as a Defense Attorney nor would Trixie blunder a simple summoning spell in the first place."   },
{   EV_NONE,    113, PP_PHOENIX  |  CMD_NONE,   "Actually... Rainbow Dash, forget what I said. Go for it, make it hurt."   },
{   EV_NONE,    108, PP_RAINBOW  |  CMD_NONE,   "Gladly!"   },
{   EV_NONE,    101, PP_TWILIGHT |  CMD_NONE,   "Phoenix! Rainbow Dash! Stop it!"   },
{   EV_NONE,    102, PP_TWILIGHT |  CMD_NONE,   "Trixie, I didn't mean to humiliate you -- please don't take this out on my friends."   },
{   EV_NONE,    116, PP_TRIXIE   |  CMD_NONE,   "Hmph! It's too late for that..."   },
{   EV_NONE,    114, PP_TRIXIE   |  CMD_NONE,   "Now if you will excuse Trixie, she must prepare for her GRAND debut as an EXTRAVAGANT and BENEVOLENT Prosecutor!"   },
{   EV_NONE,    103, PP_TWILIGHT |  CMD_STOPMUS,"Phoenix... you know what you said about Prosecutors being stuck up, smug, and arrogant...?"   },
{   EV_NONE,    103, PP_PHOENIX  |  CMD_NONE,   "Yes?"   },
{   EV_NONE,    107, PP_TWILIGHT |  CMD_NONE,   "I guess we have those here in Equestria as well..."   },
{   EV_NONE,    107, PP_PHOENIX  |  CMD_NONE,   "Who was that?"   },
{   EV_NONE,    102, PP_TWILIGHT |  CMD_NONE,   "She's a traveling performer named Trixie."   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "I kind of got her name down a long time ago; she only said it about a dozen times..."   },
{   EV_NONE,    105, PP_RAINBOW  |  CMD_NONE,   "Actually, she only said it twelve times, not a dozen."   },
{   EV_NONE,    105, PP_PHOENIX  |  CMD_NONE,   "Rainbow Dash, a dozen IS twelve."   },
{   EV_NONE,    106, PP_RAINBOW  |  CMD_NONE,   "Oh, I didn't know that... it would have been easier if you had just said twelve."   },
{   EV_NONE,    105, PP_PHOENIX  |  CMD_NONE,   "Ugh, anyway. How do you know that prosecutor, Twilight?"   },
{   EV_NONE,    117, PP_TWILIGHT |  CMD_MUSTROUPE, "I didn't know her as a prosecutor, I don't even know when that happened..."   },
{   EV_NONE,    117, PP_TWILIGHT |  CMD_NONE,   "She came to Ponyville a while ago showing off her magical talents."   },
{   EV_NONE,    117, PP_PHOENIX  |  CMD_NONE,   "Magical talents? Like magic tricks? She kinda looked like a magician judging by the attire."   },
{   EV_NONE,    117, PP_TWILIGHT |  CMD_NONE,   "Yes. Like me, she's a unicorn and she had a habit of running her mouth about her magical abilities, claiming she was the most magically gifted unicorn in Equestria."   },
{   EV_NONE,    117, PP_PHOENIX  |  CMD_NONE,   "Running her mouth is kind of an understatement... She seemed to have some sort of grudge against you, what happened?"   },
{   EV_NONE,    117, PP_TWILIGHT |  CMD_NONE,   "How should I put this... I-"   },
{   EV_NONE,    117, PP_RAINBOW  |  CMD_NONE,   "Twilight totally showed up that snob by fixing up a mess she caused!"   },
{   EV_NONE,    117, PP_TWILIGHT |  CMD_NONE,   "Well... yeah..."   },
{   EV_NONE,    104, PP_RAINBOW  |  CMD_NONE,   "Trixie is just jealous because Twilight is better with magic."   },
{   EV_NONE,    105, PP_PHOENIX  |  CMD_STOPMUS, "\"The mighty don't flaunt their power. The sly eagle hides its claws.\""   },
{   EV_NONE,    110, PP_TWILIGHT |  CMD_NONE,   "Phoenix! I'm impressed; I didn't know you were into proverbs."   },
{   EV_NONE,    110, PP_PHOENIX  |  CMD_NONE,   "Heh, what can I say?"   },
{   EV_NONE,    110, PP_PHOENIX  |  CMD_MUSLOUNGE, "(I should really tell her I just stole that one from a video game.)"   },
{   EV_NONE,    104, PP_RAINBOW  |  CMD_NONE,   "So Nix, you think you can beat that stuck up braggart?"   },
{   EV_NONE,    104, PP_PHOENIX  |  CMD_NONE,   "(Talk about the pot calling the kettle black)."   },
{   EV_NONE,    104, PP_PHOENIX  |  CMD_NONE,   "You didn't do it, right? I am sure things will turn out fine."   },
{   EV_NONE,    118, PP_TWILIGHT |  CMD_NONE,   "This isn't Mr Wright's first murder trial, Rainbow -- he's a professional. If anyone can get you out of this, he can. No substitute for experience!"   },
{   EV_NONE,    104, PP_RAINBOW  |  CMD_NONE,   "Right!"   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "There is something bothering me though, Twilight..."   },
{   EV_NONE,    102, PP_TWILIGHT |  CMD_NONE,   "What is it, Phoenix? Not getting cold feet, are you?"   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "No. It's just this court house looks almost exactly like the one in my world."   },
{   EV_NONE,    118, PP_TWILIGHT |  CMD_NONE,   "Of course it does. It was inspired from human architecture."   },
{   EV_NONE,    118, PP_PHOENIX  |  CMD_NONE,   "Why would it be inspired off of human architecture? Seems a little unnecessary if you ask me..."   },
{   EV_NONE,    110, PP_TWILIGHT |  CMD_NONE,   "Humans have a commendable sense of justice. The way you humans uphold the law is what must have inspired the designers of this court house."   },
{   EV_NONE,    110, PP_TWILIGHT |  CMD_NONE,   "Our criminal justice system also resembles yours as well from what I've read, so you should feel right at home."   },
{   EV_NONE,    110, PP_PHOENIX  |  CMD_NONE,   "I just hope justice swings in our favor today..."   },
{   EV_NONE,    102, PP_TWILIGHT |  CMD_NONE,   "Do you really think the evidence we found will be enough...?"   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "I hope so..."   },
{   EV_NONE,    119, PP_TWILIGHT |  CMD_NONE,   "Hey? What's this thing? I don't remember us finding this yesterday."   },
{   EV_NONE,    120, PP_RAINBOW  |  CMD_NONE,   "Hey! That's the toy you were playing with yesterday, Nix."   },
{   EV_NONE,    120, PP_PHOENIX  |  CMD_NONE,   "Huh? Oh yeah, that's mine. Must have got mixed up in the evidence we found."   },
{   EV_NONE,    120, PP_PHOENIX  |  CMD_NONE,   "AND IT'S NOT A TOY!"   },
{   EV_NONE,    120, PP_RAINBOW  |  CMD_NONE,   "Haha! Whatever you say."   },
{   EV_NONE,    121, PP_PHOENIX  |  CMD_NONE,   "Can you hand that over here, Twilight?"   },
{   EV_NONE,    121, PP_PHOENIX  |  CMD_NONE,   "(I should really keep a better eye on it, Maya will kill me if I lose it.)"   },
{   EV_NONE,    121, PP_TWILIGHT |  CMD_STOPMUS, "Sure, here you go."   },
{   EV_NONE,    122, PP_TWILIGHT | CMD_BADMAGSFX, ""   },
{   EV_NONE,    122, PP_PHOENIX  |  CMD_NONE,   "Huh?"   },
{   EV_NONE,    122, PP_PHOENIX  |  CMD_WHITE,  "What the?!"   }, 
{   EV_NONE,    105, PP_RAINBOW  |  CMD_NONE,   "Whoa! Are you two okay?"   },
{   EV_NONE,    123, PP_TWILIGHT |  CMD_NONE,   "Phoenix, what was that?!"   },
{   EV_NONE,    123, PP_PHOENIX  |  CMD_NONE,   "I-I don't know, it's never done that before."   },
{   EV_NONE,    107, PP_TWILIGHT |  CMD_NONE,   "You still haven't told me what that thing is yet..."   },
{   EV_NONE,    107, PP_TWILIGHT |  CMD_NONE,   "That light it just emitted, it felt... mystical..."   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "It allows me to-"   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "(Should I really tell her what it does? It would be awkward if I told her I can see deep secrets people are hiding...)"   },
{   EV_NONE,    107, PP_TWILIGHT |  CMD_NONE,   "It allows you to what?"   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "...it allows me to have good luck... it's a good luck charm..."   },
{   EV_NONE,    104, PP_RAINBOW  |  CMD_NONE,   "You say \"good luck charm\" -- I say \"toy\"!"   },
{   EV_NONE,    104, PP_PHOENIX  | CMD_MUSLOUNGE, "(Don't forget who is defending you, Skittles.)"   },
{   EV_NONE,    107, PP_TWILIGHT |  CMD_NONE,   "Here is your... charm. I guess we need all the good luck we can get today."   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "Right..."   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "(That was odd, it flashing like that when Twilight picked it up... it looks fine, I hope it still works...)"   },
{   EV_NONE,    107, PP_TWILIGHT |  CMD_NONE,   "Are you okay? You look a little worried..."   },
{   EV_NONE,    102, PP_PHOENIX  |  CMD_NONE,   "It's nothing..."   },
{   EV_NONE,    102, PP_GUARD    |  CMD_NONE,   "The Defense and its co-counsel are to make their way to the court room!"   },
{   EV_NONE,    110, PP_TWILIGHT |  CMD_NONE,   "Okay, Phoenix, the trial is about to start. Do your best!"   },
{   EV_NONE,    110, PP_PHOENIX  |  CMD_NONE,   "(Forget about the Magatama, I have bigger problems right now. Even with what little time I had to prepare... I've got to try my best for their sake!)"   },
{   EV_NONE,    110, PP_PHOENIX  |  CMD_NONE,   ""   },

{   11,         110, PP_NONE     | CMD_ENDSTORY, ""  }   // go to location 11

};
#endif


#ifdef LOCATION_IS_11
//      story                                        //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                           //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   EV_NONE,    80, PP_NONE     | CMD_BLACK,            "Everfree Forest. June 9th, 11:30PM"    },
{   10,         94,     PP_NONE         | CMD_ENDSTORY, ""  }   // go to location 10?

};
#endif

#ifndef LOCATION_IS_LOADER
// a value that can be referenced externally, though I don't plan to check everything
int nStorySize = sizeof(story)/sizeof(story[0]);
#endif

