#include "structures.h"

// Remember to take into account that you might have the right object earlier than normal if you are loading a save game!
// take it into account if you can!

#ifdef LOCATION_IS_0
// just story                                 //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                    //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   PP_PHOENIX,  0,  PP_NONE    | CMD_ADDEV,     "?????? ??????? June 9th, 8:??PM"  },
{   EV_NONE,     0,  PP_NONE    | CMD_MUSPROLOG, "Time for negotiations..."  },
{   EV_BADGE,    0,  PP_NONE    | CMD_ADDEV,     "Forget it, I'm not doing it!"  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "Do it or else!"  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "I don't care about that anymore..."  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "Besides... I have a better idea..."  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "WHAT?!"  },
{   EV_MAGATAMA, 0,  PP_NONE    | CMD_ADDEV,     "Enjoy the parting gift!"  },
{   EV_NONE,     1,  PP_NONE    | CMD_STOPMUS,   ""  },
{   EV_NONE,     1,  PP_NONE    | CMD_FLASH,     ""  },
{   EV_NONE,     1,  PP_NONE    | CMD_BLACK,     "June 9th, 9:43PM Wright and Co. Law Offices" },
{   EV_NONE,     3,  PP_NONE    | CMD_MUSSTEEL,  "(*ring*)"  },
{   EV_NONE,     3,  PP_PHOENIX | CMD_STOPMUS,   "Phoenix Wright and Co. Office. \"Defending YOU like it's nuttin', baby\"!"   },
{   EV_NONE,     3,  PP_PHOENIX | CMD_NONE,      "...No ...sorry... I-I don't need a vegetable dicer..." },
{   EV_NONE,     3,  PP_PHOENIX | CMD_NONE,      "I'm sure that...ugh..." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "That silly slogan Maya came up with must be what's making business this slow, I should really have it revised..." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Scratch that! I NEED to have it revised! What a ridiculous slogan! Who are we trying to attract, grade school students?" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "I guess it is a good sign though..." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "The fewer people who need an attorney the fewer problems there are in the world." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Unfortunately sunshine and smiles don't pay the bills." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Guess I can at least call it early tonight." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_BOOMSFX,   "ARGH!" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_MUSSUSPENSE,"W-what's going on!?"},
{   EV_NONE,     2,  PP_PHOENIX | CMD_FLASH,     "I can't move my body!" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "(Wait, is my hand fading away?!)" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Getting...Dizzy... am I... dying...?" },
{   1,           2,  PP_PHOENIX | CMD_ENDSTORY,  "" }   // go to location 1 (negative value to flag)
};
#endif

#ifdef LOCATION_IS_1
//      story                                 //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                    //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   EV_NONE,     4,  PP_NONE    | CMD_BLACK,     "?????????????? June 9th, 9:45PM"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "Ughhhhh..."  },
{   EV_NONE,     4,  PP_UNKNOWN | CMD_BLACK,     "Hey! Who the heck are you?!"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(...Whose voice is that?)"  },
{   EV_NONE,     4,  PP_UNKNOWN | CMD_BLACK,     "For that matter WHAT the heck are you?"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(\"What am I?\" What kind of question is that, does she mean my profession?)"  },
{   EV_NONE,     4,  PP_UNKNOWN | CMD_BLACK,     "I wanted the best Defense Attorney in Equestria, not some... porcupine thing."  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(*Sigh* Does my hair really look like a porcupine...?)"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(My muscles are coming to, I think I can open my eyes.)"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_NONE,      "Huh? Where am I?"  },
{   EV_NONE,     5,  PP_UNKNOWN | CMD_NONE,      "Hey! You're a human, aren't you?"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "Yeah... I'm a human..."  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_FLASH,     "WAIT WHAT?!"  },
{   EV_NONE,     6,  PP_UNKNOWN | CMD_MUSTRUCY,  "A human in Equestria, that's amazing!"  },
{   EV_NONE,     6,  PP_PHOENIX | CMD_NONE,      "Y-YOU'RE A TALKING HORSE!"  },
{   EV_NONE,     7,  PP_UNKNOWN | CMD_NONE,      "Excuse me! I am not a horse, I happen to be a pony."  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "OH! Okay! A talking PONY. That explains everything!"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "I must be in a dream... a really REALLY bad dream."  },
{   EV_NONE,     7,  PP_UNKNOWN | CMD_NONE,      "I'm pretty sure you're not, let's conduct an experiment..."  },
{   EV_NONE,     7,  PP_PHOENIX | CMD_FLASH,     "Ow! What was that for?!"  },
{   EV_NONE,     8,  PP_UNKNOWN | CMD_NONE,      "You acknowledged pain, therefore that definitely means you aren't dreaming."  },
{   EV_NONE,     8,  PP_PHOENIX | CMD_NONE,      "(This thing has a really sick sense of humor.)"  },
{   EV_NONE,     5,  PP_UNKNOWN | CMD_NONE,      "Wait... are you a defense attorney?"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "Of course I am!"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "(Why am I talking to it?!)"  },
{   EV_NONE,     9,  PP_UNKNOWN | CMD_NONE,      "Oh... oops... my mistake."  },
{   EV_NONE,     9,  PP_PHOENIX | CMD_NONE,      "What do you mean \"oops\"?"  },
{   EV_NONE,     7,  PP_UNKNOWN | CMD_NONE,      "Well, I cast a spell to call upon \"The Greatest Defense Attorney in Equestria\""  },
{   EV_NONE,     7,  PP_PHOENIX | CMD_NONE,      "What is Equestria?"  },
{   EV_NONE,    10,  PP_UNKNOWN | CMD_NONE,      "The name of this country."  },
{   EV_NONE,    11,  PP_PHOENIX | CMD_NONE,      "But I'm not FROM this country!"  },
{   EV_NONE,    10,  PP_UNKNOWN | CMD_NONE,      "I must have left out the \"Equestria\" part when I cast the spell."  },
{   EV_NONE,     9,  PP_UNKNOWN | CMD_NONE,      "I guess I accidentally called upon \"The Greatest Defense Attorney\" period."  },
{   EV_NONE,     9,  PP_UNKNOWN | CMD_NONE,      "Go figure, huh?"  },
{   EV_T_SNDBCK, 9,  PP_PHOENIX | CMD_ADDPROMPT, "Send me back"  },
{   EV_T_WHORU,  9,  PP_PHOENIX | CMD_ADDPROMPT, "Who are you?"  },
{   EV_NONE,     9,  PP_PHOENIX | CMD_NONE,      "(Oh cosmos, you flatter me.)"  },
{   EV_NONE,     9,  PP_PHOENIX | CMD_SELPROMPT, ""  },

{  EV_T_SNDBCK,  5 , PP_PHOENIX  | CMD_NONE,     "Well, can you please send me back... like RIGHT NOW?!"  },
{   EV_NONE,     10, PP_UNKNOWN  | CMD_NONE,     "Sure thing..."  },
{   EV_NONE,     6 , PP_UNKNOWN  | CMD_NONE,     "Actually... this is perfect!"  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "(Oh please don't tell me this is going where I think it is...)"  },
{   EV_NONE,     10, PP_UNKNOWN  | CMD_NONE,     "You see I am in need of a really good defense attorney..."  },
{   EV_NONE,     10, PP_PHOENIX  | CMD_NONE,     "(... aaaaaaand it does go where I think it is...)"  },
{   EV_NONE,     6 , PP_UNKNOWN  | CMD_NONE,     "And you just happen to be here..."  },
{   EV_NONE,     12, PP_PHOENIX  | CMD_NONE,     "Actually, you kidnapped me with your freaky spell, remember..."  },
{   EV_NONE,     7 , PP_UNKNOWN  | CMD_NONE,     "A minor distinction..."  },
{   EV_NONE,     7 , PP_PHOENIX  | CMD_NONE,     "MINOR!?"  },
{   EV_NONE,     6 , PP_UNKNOWN  | CMD_NONE,     "Yes... but would you be willing to represent my friend?"  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "...To be honest... I'm still shocked I am in a library talking to a purple hors-err I mean... pony..."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "Can you just send me home, please, and get someone else to do it?"  },
{   EV_NONE,     13, PP_UNKNOWN  | CMD_NONE,     "Look, I really need help... my friend's life is at stake here..."  },
{   EV_NONE,     13, PP_UNKNOWN  | CMD_SELPROMPT,""  },

{  EV_T_SNDBCK2, 5 , PP_PHOENIX  | CMD_NONE,     "Well, can you please send me back... like RIGHT NOW?!"  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "Sure thing..."  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Actually... this is perfect!"  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "(Oh please don't tell me this is going where I think it is...)"  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "You see I am in need of a really good defense attorney..."  },
{   EV_NONE,     10, PP_PHOENIX  | CMD_NONE,     "(... aaaaaaand it does go where I think it is...)"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "And you just happen to be here..."  },
{   EV_NONE,     12, PP_PHOENIX  | CMD_NONE,     "Actually, you kidnapped me with your freaky spell, remember..."  },
{   EV_NONE,     7 , PP_TWILIGHT | CMD_NONE,     "A minor distinction..."  },
{   EV_NONE,     7 , PP_PHOENIX  | CMD_NONE,     "MINOR!?"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Yes... but would you be willing to represent my friend?"  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "...Honest... I'm still shocked I am in a library talking to a purple hors-err I mean... pony..."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "Can you just send me home, please, and get someone else to do it?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Look, I really need help... my friend's life is at stake here..."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_SELPROMPT,""  },

{  EV_T_WHORU,   5 , PP_PHOENIX  | CMD_NONE,     "Let me just get my head together. This is a little too much for me."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "First off, who are you and where am I?"  },
{   PP_TWILIGHT, 10, PP_TWILIGHT | CMD_ADDEV,    "My name is Twilight Sparkle. I'm a disciple of \"Princess Celestia\", the monarch of this land."  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "I am chronicling the magic of friendship for her and you're in the town of Ponyville."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "Celestia? Magic of Friendship? Ponyville?... Wait a minute, are you saying there are more talking ponies?!"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Mhm, almost all of Ponyville's inhabitants are ponies."  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "Oh joy, this keeps getting better and better."  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "Hey, I know! Be right back!"  },
{   EV_NONE,     4 , PP_PHOENIX  | CMD_NONE,     "(Whoa! Is she moving books around with that horn?)"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Found it! Here you go! You're new here, so you can read this... uh... \"detailed\" encyclopedia of the different ponies in Equestria."  },
{   EV_NONE,     14, PP_PHOENIX  | CMD_NONE,     "Hmmm... wait! This says it's \"For early ages\" on the cover!"  },
{   EV_NONE,     14, PP_PHOENIX  | CMD_NONE,     "This is a children's book!"  },
{   EV_NONE,     9 , PP_TWILIGHT | CMD_NONE,     "Well you see... this stuff is kind of common knowledge."  },
{   EV_FILLIES,  15, PP_NONE     | CMD_ADDEV,    "The Fillies Guide to Ponies: Earth Ponies founded Land. Unicorns use magic. Pegasi soar through the air."  },
{   EV_NONE,     9 , PP_PHOENIX  | CMD_NONE,     "You call this detailed! I read the whole book cover to cover in ten seconds flat..."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_STOPMUS,  "*Sigh*"  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Hey... I'm sorry. I guess I shouldn't look a gift horse in the mouth."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "(Should I have said Pony there, I wonder...)"  },
{   EV_T_SNDBCK, EV_T_SNDBCK2, PP_PHOENIX  | CMD_CHANGEPROMPT, ""  }, // update target of SNDBCK since we know the name now
{   EV_T_CRIME,  13, PP_PHOENIX  | CMD_ADDPROMPT,"What was the crime?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "No, it's not that. It's my friend... I know she is not guilty but she is going to be punished for a crime she didn't even commit."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_SELPROMPT,""  },

{  EV_T_CRIME,   13, PP_PHOENIX  | CMD_NONE,     "What kind of crime is she being accused of?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Murder..."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "(Surprise, surprise...)"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Murder never happens in Ponyville, or Equestria for that matter, so the punishment is very severe."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "What is the punishment?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Banishment..."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Well that isn't so bad compared to-"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "To the moon... or even the sun..."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "I have convinced the Princess to go easy on her but she will have no choice if the verdict ends up being guilty."  },
{   EV_T_DETAIL, 9,  PP_PHOENIX  | CMD_ADDPROMPT,"Any details?"  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "(And forget what I just said, sheesh! If being sent to the sun is \"going easy on someone\" then remind me never to do anything bad in this place.)"  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_SELPROMPT,""  },

{   EV_T_DETAIL, 13, PP_PHOENIX  | CMD_NONE,     "So...uh...Twilight, do you know any details about the crime?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Not much, all I know was my friend was near the scene of the crime when the murder took place. That is why she's the prime suspect."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Where is she right now?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "In the Ponyville Detention Center."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Have you spoken with her since?"  },
{   EV_NONE,     5 , PP_TWILIGHT | CMD_NONE,     "I would but the guards won't let me in."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "They won't let you in? Why not?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "I can only get in there with a Defense Attorney which is why I was trying to call one."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Okay then. Since I'm a Defense Attorney, let's go to this Detention Center."  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_MUSTRUCY, "Really! So you'll take the case?!"  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "Hey hey... I haven't decided that yet. I just thought the least I could do is help you get in to speak with your friend."  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Thank you for your kindness, Phoenix Wright."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_STOPMUS,  "How did you know my name? I haven't introduced myself yet..."  },
{   EV_NONE,     16, PP_TWILIGHT | CMD_NONE,     "Oh-uh... I did... uh.. a quick identification spell."  },
{   EV_NONE,     16, PP_PHOENIX  | CMD_NONE,     "Identification spell?"  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "Yeah! An identification spell! Anyway, let me prepare a few things, then we can go to the Detention Center."  },
{   EV_NONE,     4,  PP_PHOENIX  | CMD_NONE,     "(After I get her inside there with her friend, I'll let her off easy and make her send me back home. There is no way I'm taking a case this weird...)"  },
{   2,           4 , PP_PHOENIX  | CMD_ENDSTORY, ""  }
};

#endif

#ifdef LOCATION_IS_2
//      story                                    //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                       //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   EV_NONE,    17,     PP_NONE     | CMD_NONE,     "Ponyville June 9th, 10:05PM"   },
{   EV_NONE,    17,     PP_PHOENIX  | CMD_NONE,     "I have never felt like such a minority in my life!"    },
{   EV_NONE,    18,     PP_TWILIGHT | CMD_NONE,     "Oh, it wasn't that bad."   },
{   EV_NONE,    18,     PP_PHOENIX  | CMD_NONE,     "All those ponies were gawking at me the whole way here!"   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_NONE,     "Mr. Wright, humans have almost never been seen in Equestria."   },
{   EV_NONE,    18,     PP_TWILIGHT | CMD_NONE,     "In fact you may be the first one in Ponyville."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "You should be honored!"   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_NONE,     "(Honored? Strolling around a town infested with candy colored equines...)"   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_NONE,     "(Yeah, maybe I'd feel honored if I was... Oh, I dunno... a five year old girl!)"   },

{   EV_T_HUMAN, 20,     PP_PHOENIX  | CMD_ADDPROMPT, "How did you know?"  },
{   EV_T_NOHUMAN, 20,   PP_PHOENIX  | CMD_ADDPROMPT, "Let it go"  },
{   EV_NONE,     20,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_HUMAN, 20,     PP_PHOENIX  | CMD_NONE,     "So how did you know I was a human?"   },
{   EV_NONE,    21,     PP_TWILIGHT | CMD_NONE,     "I read a lot!"   },
{   EV_NONE,    21,     PP_TWILIGHT | CMD_NONE,     "I've read almost every book in my library five times over and I am familiar with a lot of different species:"   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "Chimeras, Trolls, Basilisks, Goblins, et cetera, et cetera."   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_NONE,     "(Wait!? You're telling me she has read every book in that gigantic library FIVE TIMES?!)"   },

{   EV_T_NOHUMAN, 19,   PP_TWILIGHT | CMD_NONE,     "Anyway we're here, Phoenix."   },
{   PP_GUARD,   22,     PP_GUARD    | CMD_ADDEV,    "Halt! Only a lawyer can enter the detention center."   },
{   EV_NONE,    18,     PP_TWILIGHT | CMD_NONE,     "Well, go on..."   },
{   EV_NONE,    22,     PP_PHOENIX  | CMD_NONE,     "Uh... Hi guys, I'm a lawyer..."   },
{   EV_NONE,    22,     PP_GUARD    | CMD_NONE,     "Identification!"   },

{   EV_NONE,    22,     PP_GUARD    | CMD_SHOWEV,   "Present your identification"   },
{   EV_BADGE,EV_T_LAWYERBADGE, PP_GUARD|CMD_JUMPIFSHOW, "" }, 
{  EV_E_BADGE,EV_T_RIGHTBADGE, PP_GUARD|CMD_JUMPIFSHOW, "" }, 
{   EV_T_NOBADGE,22,    PP_GUARD    | CMD_JUMP,     "" }, 

{   EV_T_LAWYERBADGE, 22, PP_PHOENIX| CMD_NONE,     "Ah!... Right here!"   },
{   EV_NONE,    23,     PP_PHOENIX  | CMD_NONE,     "(Never leave home without it!)"   },
{   EV_NONE,    23,     PP_GUARD    | CMD_NONE,     "What is that?"   },
{   EV_NONE,    23,     PP_GUARD    | CMD_NONE,     "Is that a toy? You look a little old to be playing with toys."   },
{   EV_NONE,    23,     PP_PHOENIX  | CMD_NONE,     "(Next time I am leaving it at home...)"   },

{   EV_T_NOBADGE,22,    PP_GUARD    | CMD_NONE,     "You cannot pass without valid Equestrian identification."   },
{   EV_NONE,    22,     PP_PHOENIX  | CMD_NONE,     "But I don't have any..."   },
{   EV_NONE,    22,     PP_GUARD    | CMD_NONE,     "Then beat it Spiky!"   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE,     "Twilight! They're not letting me in."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "Oh that's right, Mr. Wright! I was supposed to give you this."   },
{   EV_NONE,    24,     PP_TWILIGHT | CMD_CLRPROMPT,"The princess ordered me to give you this earlier today. A permit to defend in Equestria."   },

{   EV_T_QUESTIONBADGE,24,PP_PHOENIX| CMD_ADDPROMPT,"That seems odd..."   },
{   EV_T_NOQBADGE,24,   PP_PHOENIX | CMD_ADDPROMPT, "That's fine."        },
{   EV_NONE,     24,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{EV_T_QUESTIONBADGE,24, PP_PHOENIX  | CMD_NONE,     "I see... wait..."   },
{   EV_NONE,    25,     PP_PHOENIX  | CMD_NONE,     "I thought you accidentally brought me here. How could your princess have had that prepared for me?"   },
{   EV_NONE,    26,     PP_TWILIGHT | CMD_NONE,     "O-oh uh What I meant was... I had my assistant Spike prepare it before we left."   },
{   EV_NONE,    26,     PP_PHOENIX  | CMD_NONE,     "Spike? I didn't see anyone else in that library..."   },
{   EV_NONE,    25,     PP_TWILIGHT | CMD_NONE,     "He was sleeping. It's late as you can see, I had to wake him up and have him prepare it. That's why it took a little while to leave."   },
{   EV_NONE,    27,     PP_TWILIGHT | CMD_NONE,     "I'll properly introduce you to him later."   },
{   EV_NONE,    28,     PP_PHOENIX  | CMD_NONE,     "You prepared a permit in twenty minutes? I find that a little fishy..."   },
{   EV_NONE,    29,     PP_TWILIGHT | CMD_NONE,     "Save the questions for my friend, just take the badge!"   },
{   EV_NONE,    29,     PP_PHOENIX  | CMD_NONE,     "(This isn't helping me accept your request, you know...)"   },

{ EV_T_NOQBADGE,30,     PP_PHOENIX  | CMD_CHIMESFX, "Equestrian Attorney Badge. A heart shaped badge that gives all the privileges of an Equestrian defense attorney."  },
{ EV_E_BADGE,   19,     PP_PHOENIX  | CMD_ADDEV,    "A heart..."   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE,     "(I feel my masculinity going... going... gone.)"   },
{   EV_NONE,    31,     PP_TWILIGHT | CMD_NONE,     "Come on, hurry up! Visiting hours are almost over."   },
{   EV_NONE,    31,     PP_PHOENIX  | CMD_NONE,     "Alright, alright! No need to shove me..."   },
{   EV_NONE,    32,     PP_PHOENIX  | CMD_NONE,     "Okay... guys here it is..."   },
{   EV_NONE,    32,     PP_PHOENIX  | CMD_NONE,     "(This is so degrading...)"   },

{ EV_T_RIGHTBADGE,32,   PP_GUARD    | CMD_NONE,     "Permission granted, you may enter."   },
{   EV_NONE,    32,     PP_PHOENIX  | CMD_NONE,     "Phew... alrighty!"   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE,     "Come on Twilight, you can go speak with your friend now."   },
{   EV_NONE,    33,     PP_TWILIGHT | CMD_NONE,     "Sorry Phoenix..."   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "Sorry? About what?"   },
{   EV_NONE,    33,     PP_TWILIGHT | CMD_NONE,     "I am not allowed in, only attorneys are allowed to speak with suspects..."   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "But you said..."   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_NONE,     "I know I said I'd talk to her but it'd be better if you got all the details about the crime to make your judgement."   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_NONE,     "Just please hear her out... if you don't want to do it after that..."   },
{   EV_NONE,    33,     PP_TWILIGHT | CMD_NONE,     "I'll send you back to where you came from..."   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_CLRPROMPT, "But I-"   },

{   EV_T_CONCERN,24,    PP_PHOENIX  | CMD_ADDPROMPT, "Concerned..."   },
{   EV_T_NOCONCERN,24,  PP_PHOENIX  | CMD_ADDPROMPT, "See what it's all about."        },
{   EV_NONE,     24,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_CONCERN, 33,   PP_PHOENIX  | CMD_NONE,     "(Should I really be doing this...?)"   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "(Should I really be meddling in some other world's affair...?)"   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "(Maybe I should at least hear what all this fuss is about...)"   },

{ EV_T_NOCONCERN, 33,   PP_PHOENIX  | CMD_NONE,     "Sigh... Fine..."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "Thank you so much, Mr. Wright."   },
{   3,          20,     PP_NONE     | CMD_ENDSTORY, ""  }   // go to location 3

};
#endif

#ifdef LOCATION_IS_3
//      story                                    //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                       //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901

{   EV_NONE,    34,     PP_NONE     | CMD_NONE,     "Ponyville Detention Center June 9th, 10:15PM"      },
{   EV_NONE,    34,     PP_PHOENIX  | CMD_NONE,     "Okay, so where is Twilight's friend?"      },
{   EV_NONE,    35,     PP_UNKNOWN  | CMD_CHIMESFX, "Hey!"      },
{   EV_NONE,    35,     PP_PHOENIX  | CMD_NONE,     "Eh?! What did I do?!"      },
{   EV_NONE,    36,     PP_UNKNOWN  | CMD_NONE,     "I don't think they allow animals in here, you should get out before they toss you in here too."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Look, I am not an animal. I'm a human being!"      },
{   EV_NONE,    37,     PP_UNKNOWN  | CMD_NONE,     "Oh... I didn't mean you, I meant that thing on your head."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "(If someone makes fun of my hair ONE more time...)"      },
{   EV_NONE,    37,     PP_UNKNOWN  | CMD_MUS??,    "So I'm guessing you're my lawyer, huh?"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "Yes, Twilight Sparkle sent me..."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_BOOMSFX,  "Wait! No! I haven't agreed to anything yet!"      },
{   EV_NONE,    38,     PP_UNKNOWN  | CMD_NONE,     "Geez, Twilight knows how to pick 'em..."      },
{   EV_NONE,    36,     PP_UNKNOWN  | CMD_NONE,     "What are you doing here then?"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "I just want information regarding the crime you are being accused of."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Let's start off with your name..."      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "I'm Rainbow Dash, best flier in Ponyville! Soon to be a household name in all of Equestria!"      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "Line up for my autograph starts over there!"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "(Twilight Sparkle? Rainbow Dash?)"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "(Is it me or are their names starting to sound like flavors of ice cream?)"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "I am Phoenix Wright, best attorney in the... universe... apparently..."      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_NONE,     "Phoenix?"      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_CHIMESFX, "Sweet name but it could sound cooler..."      },
{   EV_NONE,    39,     PP_PHOENIX  | CMD_NONE,     "Uuhh... \"cooler\"?"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "I think I'll call you \"Nix\", that sounds cool!"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "(Another strange name I can add to my nickname checklist.)"      },

{   EV_T_EARTHP, 36,    PP_PHOENIX  | CMD_ADDPROMPT, "You're an earth pony?"   },
{   EV_T_UNIP,   36,    PP_PHOENIX  | CMD_ADDPROMPT, "You're a unicorn?"   },
{   EV_T_PEGASUSP,36,   PP_PHOENIX  | CMD_ADDPROMPT, "You're a pegasus?"   },
{   EV_T_NOPONY, 36,    PP_PHOENIX  | CMD_ADDPROMPT, "Why are you in here?"    },
{   EV_NONE,     36,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "Hmmm, so you are an... earth pony, correct?"      },
{   EV_NONE,    41,     PP_RAINBOW  | CMD_NONE,     "What the hay are you talking about? I'm not an earth pony, I'm a pegasus!"      },
{EV_T_BADGUESS, 41,     PP_RAINBOW  | CMD_JUMP,     ""      },

{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "Hmmm, so you are a... unicorn pony, correct?"      },
{   EV_NONE,    41,     PP_RAINBOW  | CMD_NONE,     "What the hay are you talking about? I'm not a unicorn, I'm a pegasus!"      },
{EV_T_BADGUESS, 41,     PP_RAINBOW  | CMD_JUMP,     ""      },

{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "Hmmm, so you are a... pegasus, correct?"      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "That's right! The BEST pegasus! Good for you, Nix!"      },
{EV_T_NOPONY,   41,     PP_RAINBOW  | CMD_JUMP,     ""      },

{EV_T_BADGUESS, 41,     PP_PHOENIX  | CMD_NONE,     "(It's kinda sad I couldn't get down a book with twelve words.)"      },

{ EV_T_NOPONY,  41,     PP_PHOENIX  | CMD_NONE,     "Uhh... never mind that. Why are you in here?"      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_NONE,     "Well, I guess I can tell you all I know..."      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_CLRPROMPT,"You see, last night a pegasus named \"Ace Swift\" was killed in the Everfree Forest."      },

{   EV_T_ACE,   36,    PP_PHOENIX  | CMD_ADDPROMPT, "Ace Swift"    },
{   EV_NONE,    36,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_ACE,   36,     PP_PHOENIX  | CMD_NONE,     "Do you know anything about him?"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "Sure do, he was a hot shot racer expected to win the \"Equestrian 500\"."      },

{   EV_T_EQ500, 36,    PP_PHOENIX  | CMD_ADDPROMPT, "Equestrian 500"    },
{   EV_NONE,    36,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_EQ500, 37,     PP_PHOENIX  | CMD_NONE,     "\"Equestrian 500\"?"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "A grueling race for pegasi, enduring a five hundred mile journey around Equestria."      },
{   PP_ACE,     37,     PP_RAINBOW  | CMD_ADDEV,    "He was the top pick to win the whole thing."      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "Dont worry though..."      },

{   EV_T_DONTWORRY, 36, PP_PHOENIX  | CMD_ADDPROMPT, "Don't worry?"    },
{   EV_T_HOWDIE, 36,    PP_PHOENIX  | CMD_ADDPROMPT, "How did he die?"    },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_DONTWORRY, 39, PP_PHOENIX  | CMD_NONE,     "\"Don't worry\"? About what?"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "I still would have won even if he were still alive, ha!"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "Let me guess, you were planning on entering that race as well?"      },
{   EV_NONE,    42,     PP_RAINBOW  | CMD_NONE,     "Of course! The winner gets special lessons from the Wonderbolts!"      },
{   EV_NONE,    42,     PP_PHOENIX  | CMD_NONE,     "Who are \"The Wonderbolts\"?"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "You don't know who the Wonderbolts are?"      },
{   EV_NONE,    35,     PP_RAINBOW  | CMD_NONE,     "You living under a rock or something?!"      },
{   EV_NONE,    35,     PP_PHOENIX  | CMD_NONE,     "Hey, I'm new here! Cut me some slack!"      },
{   EV_NONE,    43,     PP_RAINBOW  | CMD_NONE,     "*Sigh*"      },
{   EV_NONE,    41,     PP_RAINBOW  | CMD_NONE,     "\"THE\" Wonderbolts are only the most coolest ponies in all of Equestria!"      },
{   EV_NONE,    41,     PP_RAINBOW  | CMD_NONE,     "They are the Princess' personal aerial acrobatic team. The stunts they perform are nine degrees of cool!"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "You see, I've been trying to get in their group forever and the Equestrian 500 is my ticket to show off my slick moves to them."      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "I'd do anything to get that chance!"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "(Thank you for effectively establishing motive for yourself, Ms. Dash, this helps your case so much...)"      },

{   EV_NONE,    36,     PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_HOWDIE, 37,    PP_PHOENIX  | CMD_NONE,     "So how did this guy die?"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "Pony."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Wha...?"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "\"How did this pony die?\" is what you mean, Nix."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "(Well excuse me, I didn't take \"Hooked on Ponyics\")"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "The point is, how did he die?"      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_NONE,     "How should I know? I didn't do it..."      },

{   EV_T_ARREST,36,    PP_PHOENIX  | CMD_ADDPROMPT, "Arrest?"    },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_ARREST,40,     PP_PHOENIX  | CMD_NONE,     "Then why did they take you in?"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "I just happened to be flying near the Everfree Forest that night..."      },
{   EV_NONE,    35,     PP_RAINBOW  | CMD_NONE,     "Then those chuckleheads burst into my house and brought me here, saying \"I did it\"!"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "They even said that they had lots of proof but I would never do that to another pony!"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "They just took you in like that?"      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_STOPMUS,  "They said they are going to banish me..."      },
{   EV_NONE,    45,     PP_PHOENIX  | CMD_NONE,     "So I heard..."      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_MUS???,     "Everyone thinks I did it, everyone!"      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_NONE,     "The Wonderbolts probably hate me..."      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "But you believe me, right?"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Well, I-I guess, but not everyone thinks you did it..."      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_NONE,     "Huh?"      },
{   EV_NONE,    40,     PP_PHOENIX  | CMD_NONE,     "Your friend Twilight seems to have faith in you, otherwise I wouldn't be in this mess..."      },
{   EV_NONE,    44,     PP_RAINBOW  | CMD_NONE,     "Heh, you're right I guess. Twilight's a real pal..."      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "What do you mean by \"mess\", anyway?"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "You see, as you can probably guess I'm not from Equestria."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Your purple friend pulled me out of my world because she accidentally called the \"Greatest Defense Attorney\"... and that happened to be me."      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "Awesome! It's only fitting, the best pegasus ever gets the best lawyer ever!"      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "You were destined to defend me!"      },
{   EV_NONE,    39,     PP_PHOENIX  | CMD_NONE,     "(The ones ego is larger than Detective Gumshoe's appetite for instant noodles.)"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "Nix, as much as I hate asking for help..."      },
{   EV_NONE,    44,     PP_RAINBOW  | CMD_NONE,     "Can you PAH-LEEES be my Attorney?"      },
{   EV_NONE,    44,     PP_PHOENIX  | CMD_CLRPROMPT,"(I feel kind of sorry for her, she sounds like she is telling the truth and I want to say yes... but should I...?)"      },

{   EV_T_BELIEVE,36,    PP_PHOENIX  | CMD_ADDPROMPT, "Believe her"    },
{   EV_T_MAKESURE,36,   PP_PHOENIX  | CMD_ADDPROMPT, "Make sure"    },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_BELIEVE,44,    PP_PHOENIX  | CMD_NONE,     "Well... oh, wait a minute!"      },
{   EV_NONE,    46,     PP_PHOENIX  | CMD_NONE,     "(I believe her but I better make sure...)"      },

{   EV_T_MAKESURE, 47,  PP_PHOENIX  | CMD_NONE,     "Magatama: A gift from Maya. Allows me to see if anyone is hiding any deep secret in their heart from me."  },

{   EV_NONE,    48,     PP_RAINBOW  | CMD_NONE,     "Is that a toy? You look a little old to be playing with toys, Nix."      },
{   EV_NONE,    49,     PP_PHOENIX  | CMD_NONE,     "Look, Rainbow Dash, I am going to ask you this and I want you to tell me the absolute 100% truth!"      },
{   EV_NONE,    49,     PP_PHOENIX  | CMD_STOPMUS,  "Did you have ANYTHING to do with the death of \"Ace Swift\"?"      },
{   EV_NONE,    50,     PP_RAINBOW  | CMD_CRASHSFX, "I told you... I DIDN'T KILL ANYPONY!"      },
{   EV_NONE,    50,     PP_PHOENIX  | CMD_NONE,     "..."      },
{   EV_NONE,    49,     PP_PHOENIX  | CMD_NONE,     "(Nothing... it's certain then. She really didn't do it.)"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Okay Rainbow Dash..."      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "What? Why did you go all silent there?"      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "I've decided to take your case, I trust you."      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_MUS???,     "Yes! Alright! I know you can do it Nix!"      },
{   EV_NONE,    39,     PP_PHOENIX  | CMD_NONE,     "I suppose the first thing I should do is investigate the scene of the crime for some evidence to prove your innocence. Where was it again?"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "A clearing in the Everfree Forest."      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "Everfree Forest?"      },
{   EV_NONE,    36,     PP_RAINBOW  | CMD_NONE,     "Yeah, it's about fifteen minutes from Fluttershy's house."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "Fluttershy... huh..."      },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_NONE,     "(Probably another pony...)"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "Well good luck Nix, you may look a little strange but you're okay in my book!"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "(\"I\" look a little strange?! Coming from the \"Roy G Biv\" pony with wings, you look strange even by Ponyville standards!)"      },
{   EV_NONE,    37,     PP_PHOENIX  | CMD_NONE,     "Oh... right, there was one more question I wanted to ask you..."      },
{   EV_NONE,    40,     PP_RAINBOW  | CMD_CLRPROMPT,"Shoot!"      },

{   EV_T_WHYTHERE,36,   PP_PHOENIX  | CMD_ADDPROMPT, "What were you doing?"    },
{   EV_NONE,    36,     PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_WHYTHERE, 40,  PP_PHOENIX  | CMD_NONE,     "What were you doing near the scene of the crime anyway?"      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_STOPMUS,  "Uh..."      },
{   EV_NONE,    45,     PP_PHOENIX  | CMD_NONE,     "Well?"      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_NONE,     "I-I was practicing for the Equestrian 500."      },
{   EV_NONE,    51,     PP_RAINBOW  | CMD_LOCKSFX,  "Yep, that's what I was doing... practicing for the big race!"      },
{   EV_NONE,    52,     PP_PHOENIX  | CMD_NONE,     "(Psyche-locks... you're a bad liar. Even without this thing I can tell that you are hiding something from me.)"      },
{   EV_NONE,    38,     PP_PHOENIX  | CMD_NONE,     "Look Rainbow Dash, if I am going to defend you, you're going to need to be honest with me..."      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_NONE,     "I told you a dozen times already, I didn't do it!"      },
{   EV_NONE,    35,     PP_PHOENIX  | CMD_NONE,     "I am not saying you did it! I'm just wondering what you were doing near the scene of the crime."      },
{   EV_NONE,    45,     PP_RAINBOW  | CMD_NONE,     "Um... well... uh-oh...!"      },
{   EV_NONE,    37,     PP_RAINBOW  | CMD_NONE,     "Looks like visiting hours are over!"      },
{   EV_NONE,    39,     PP_RAINBOW  | CMD_NONE,     "Catch ya later, Nix!"      },
{   EV_NONE,    34,     PP_PHOENIX  | CMD_NONE,     "Hey! No they aren't! There are still five minutes left!"      },
{   EV_NONE,    34,     PP_PHOENIX  | CMD_NONE,     "She's gone..."      },
{   EV_NONE,    34,     PP_PHOENIX  | CMD_NONE,     "Oh well, I probably need more information to pursue that any further anyway. As long as she didn't do it that is all I need to know for now."      },
    
{   4,          34,     PP_NONE     | CMD_ENDSTORY, ""  }   // go to location 4

};
#endif


#ifndef LOCATION_IS_LOADER
// a value that can be referenced externally, though I don't plan to check everything
int nStorySize = sizeof(story)/sizeof(story[0]);
#endif

