#include "structures.h"

// Remember to take into account that you might have the right object earlier than normal if you are loading a save game!
// take it into account if you can!

#ifdef LOCATION_IS_0
// just story                                 //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                    //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   PP_PHOENIX,  0,  PP_NONE    | CMD_ADDEV,     "?????? ??????? June 9th, 8:??PM"  },
{   EV_NONE,     0,  PP_NONE    | CMD_MUSPROLOG, "Time for negotiations..."  },
{   EV_BADGE,    0,  PP_NONE    | CMD_ADDEV,     "Forget it, I'm not doing it!"  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "Do it or else!"  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "I don't care about that anymore..."  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "Besides... I have a better idea..."  },
{   EV_NONE,     0,  PP_NONE    | CMD_NONE,      "WHAT?!"  },
{   EV_MAGATAMA, 0,  PP_NONE    | CMD_ADDEV,     "Enjoy the parting gift!"  },
{   EV_NONE,     1,  PP_NONE    | CMD_STOPMUS,   ""  },
{   EV_NONE,     1,  PP_NONE    | CMD_FLASH,     ""  },
{   EV_NONE,     1,  PP_NONE    | CMD_BLACK,     "June 9th, 9:43PM Wright and Co. Law Offices" },
{   EV_NONE,     3,  PP_NONE    | CMD_MUSSTEEL,  "(*ring*)"  },
{   EV_NONE,     3,  PP_PHOENIX | CMD_STOPMUS,   "Phoenix Wright and Co. Office. \"Defending YOU like it's nuttin', baby\"!"   },
{   EV_NONE,     3,  PP_PHOENIX | CMD_NONE,      "...No ...sorry... I-I don't need a vegetable dicer..." },
{   EV_NONE,     3,  PP_PHOENIX | CMD_NONE,      "I'm sure that...ugh..." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "That silly slogan Maya came up with must be what's making business this slow, I should really have it revised..." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Scratch that! I NEED to have it revised! What a ridiculous slogan! Who are we trying to attract, grade school students?" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "I guess it is a good sign though..." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "The fewer people who need an attorney the fewer problems there are in the world." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Unfortunately sunshine and smiles don't pay the bills." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Guess I can at least call it early tonight." },
{   EV_NONE,     2,  PP_PHOENIX | CMD_BOOMSFX,   "ARGH!" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_MUSSUSPENSE,"W-what's going on!?"},
{   EV_NONE,     2,  PP_PHOENIX | CMD_FLASH,     "I can't move my body!" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "(Wait, is my hand fading away?!)" },
{   EV_NONE,     2,  PP_PHOENIX | CMD_NONE,      "Getting...Dizzy... am I... dying...?" },
{   1,           2,  PP_PHOENIX | CMD_ENDSTORY,  "" }   // go to location 1 (negative value to flag)
};
#endif

#ifdef LOCATION_IS_1
//      story                                 //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                    //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   EV_NONE,     4,  PP_NONE    | CMD_BLACK,     "?????????????? June 9th, 9:45PM"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "Ughhhhh..."  },
{   EV_NONE,     4,  PP_UNKNOWN | CMD_BLACK,     "Hey! Who the heck are you?!"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(...Whose voice is that?)"  },
{   EV_NONE,     4,  PP_UNKNOWN | CMD_BLACK,     "For that matter WHAT the heck are you?"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(\"What am I?\" What kind of question is that, does she mean my profession?)"  },
{   EV_NONE,     4,  PP_UNKNOWN | CMD_BLACK,     "I wanted the best Defense Attorney in Equestria, not some... porcupine thing."  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(*Sigh* Does my hair really look like a porcupine...?)"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_BLACK,     "(My muscles are coming to, I think I can open my eyes.)"  },
{   EV_NONE,     4,  PP_PHOENIX | CMD_NONE,      "Huh? Where am I?"  },
{   EV_NONE,     5,  PP_UNKNOWN | CMD_NONE,      "Hey! You're a human, aren't you?"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "Yeah... I'm a human..."  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_FLASH,     "WAIT WHAT?!"  },
{   EV_NONE,     6,  PP_UNKNOWN | CMD_MUSTRUCY,  "A human in Equestria, that's amazing!"  },
{   EV_NONE,     6,  PP_PHOENIX | CMD_NONE,      "Y-YOU'RE A TALKING HORSE!"  },
{   EV_NONE,     7,  PP_UNKNOWN | CMD_NONE,      "Excuse me! I am not a horse, I happen to be a pony."  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "OH! Okay! A talking PONY. That explains everything!"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "I must be in a dream... a really REALLY bad dream."  },
{   EV_NONE,     7,  PP_UNKNOWN | CMD_NONE,      "I'm pretty sure you're not, let's conduct an experiment..."  },
{   EV_NONE,     7,  PP_PHOENIX | CMD_FLASH,     "Ow! What was that for?!"  },
{   EV_NONE,     8,  PP_UNKNOWN | CMD_NONE,      "You acknowledged pain, therefore that definitely means you aren't dreaming."  },
{   EV_NONE,     8,  PP_PHOENIX | CMD_NONE,      "(This thing has a really sick sense of humor.)"  },
{   EV_NONE,     5,  PP_UNKNOWN | CMD_NONE,      "Wait... are you a defense attorney?"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "Of course I am!"  },
{   EV_NONE,     5,  PP_PHOENIX | CMD_NONE,      "(Why am I talking to it?!)"  },
{   EV_NONE,     9,  PP_UNKNOWN | CMD_NONE,      "Oh... oops... my mistake."  },
{   EV_NONE,     9,  PP_PHOENIX | CMD_NONE,      "What do you mean \"oops\"?"  },
{   EV_NONE,     7,  PP_UNKNOWN | CMD_NONE,      "Well, I cast a spell to call upon \"The Greatest Defense Attorney in Equestria\""  },
{   EV_NONE,     7,  PP_PHOENIX | CMD_NONE,      "What is Equestria?"  },
{   EV_NONE,    10,  PP_UNKNOWN | CMD_NONE,      "The name of this country."  },
{   EV_NONE,    11,  PP_PHOENIX | CMD_NONE,      "But I'm not FROM this country!"  },
{   EV_NONE,    10,  PP_UNKNOWN | CMD_NONE,      "I must have left out the \"Equestria\" part when I cast the spell."  },
{   EV_NONE,     9,  PP_UNKNOWN | CMD_NONE,      "I guess I accidentally called upon \"The Greatest Defense Attorney\" period."  },
{   EV_NONE,     9,  PP_UNKNOWN | CMD_NONE,      "Go figure, huh?"  },
{   EV_T_SNDBCK, 9,  PP_PHOENIX | CMD_ADDPROMPT, "Send me back"  },
{   EV_T_WHORU,  9,  PP_PHOENIX | CMD_ADDPROMPT, "Who are you?"  },
{   EV_NONE,     9,  PP_PHOENIX | CMD_NONE,      "(Oh cosmos, you flatter me.)"  },
{   EV_NONE,     9,  PP_PHOENIX | CMD_SELPROMPT, ""  },

{  EV_T_SNDBCK,  5 , PP_PHOENIX  | CMD_NONE,     "Well, can you please send me back... like RIGHT NOW?!"  },
{   EV_NONE,     10, PP_UNKNOWN  | CMD_NONE,     "Sure thing..."  },
{   EV_NONE,     6 , PP_UNKNOWN  | CMD_NONE,     "Actually... this is perfect!"  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "(Oh please don't tell me this is going where I think it is...)"  },
{   EV_NONE,     10, PP_UNKNOWN  | CMD_NONE,     "You see I am in need of a really good defense attorney..."  },
{   EV_NONE,     10, PP_PHOENIX  | CMD_NONE,     "(... aaaaaaand it does go where I think it is...)"  },
{   EV_NONE,     6 , PP_UNKNOWN  | CMD_NONE,     "And you just happen to be here..."  },
{   EV_NONE,     12, PP_PHOENIX  | CMD_NONE,     "Actually, you kidnapped me with your freaky spell, remember..."  },
{   EV_NONE,     7 , PP_UNKNOWN  | CMD_NONE,     "A minor distinction..."  },
{   EV_NONE,     7 , PP_PHOENIX  | CMD_NONE,     "MINOR!?"  },
{   EV_NONE,     6 , PP_UNKNOWN  | CMD_NONE,     "Yes... but would you be willing to represent my friend?"  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "...To be honest... I'm still shocked I am in a library talking to a purple hors-err I mean... pony..."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "Can you just send me home, please, and get someone else to do it?"  },
{   EV_NONE,     13, PP_UNKNOWN  | CMD_NONE,     "Look, I really need help... my friend's life is at stake here..."  },
{   EV_NONE,     13, PP_UNKNOWN  | CMD_SELPROMPT,""  },

{  EV_T_SNDBCK2, 5 , PP_PHOENIX  | CMD_NONE,     "Well, can you please send me back... like RIGHT NOW?!"  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "Sure thing..."  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Actually... this is perfect!"  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "(Oh please don't tell me this is going where I think it is...)"  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "You see I am in need of a really good defense attorney..."  },
{   EV_NONE,     10, PP_PHOENIX  | CMD_NONE,     "(... aaaaaaand it does go where I think it is...)"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "And you just happen to be here..."  },
{   EV_NONE,     12, PP_PHOENIX  | CMD_NONE,     "Actually, you kidnapped me with your freaky spell, remember..."  },
{   EV_NONE,     7 , PP_TWILIGHT | CMD_NONE,     "A minor distinction..."  },
{   EV_NONE,     7 , PP_PHOENIX  | CMD_NONE,     "MINOR!?"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Yes... but would you be willing to represent my friend?"  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "...Honest... I'm still shocked I am in a library talking to a purple hors-err I mean... pony..."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "Can you just send me home, please, and get someone else to do it?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Look, I really need help... my friend's life is at stake here..."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_SELPROMPT,""  },

{  EV_T_WHORU,   5 , PP_PHOENIX  | CMD_NONE,     "Let me just get my head together. This is a little too much for me."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "First off, who are you and where am I?"  },
{   PP_TWILIGHT, 10, PP_TWILIGHT | CMD_ADDEV,    "My name is Twilight Sparkle. I'm a disciple of \"Princess Celestia\", the monarch of this land."  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "I am chronicling the magic of friendship for her and you're in the town of Ponyville."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "Celestia? Magic of Friendship? Ponyville?... Wait a minute, are you saying there are more talking ponies?!"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Mhm, almost all of Ponyville's inhabitants are ponies."  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "Oh joy, this keeps getting better and better."  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "Hey, I know! Be right back!"  },
{   EV_NONE,     4 , PP_PHOENIX  | CMD_NONE,     "(Whoa! Is she moving books around with that horn?)"  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Found it! Here you go! You're new here, so you can read this... uh... \"detailed\" encyclopedia of the different ponies in Equestria."  },
{   EV_NONE,     14, PP_PHOENIX  | CMD_NONE,     "Hmmm... wait! This says it's \"For early ages\" on the cover!"  },
{   EV_NONE,     14, PP_PHOENIX  | CMD_NONE,     "This is a children's book!"  },
{   EV_NONE,     9 , PP_TWILIGHT | CMD_NONE,     "Well you see... this stuff is kind of common knowledge."  },
{   EV_FILLIES,  15, PP_NONE     | CMD_ADDEV,    "The Fillies Guide to Ponies: Earth Ponies founded Land. Unicorns use magic. Pegasi soar through the air."  },
{   EV_NONE,     9 , PP_PHOENIX  | CMD_NONE,     "You call this detailed! I read the whole book cover to cover in ten seconds flat..."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_STOPMUS,  "*Sigh*"  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Hey... I'm sorry. I guess I shouldn't look a gift horse in the mouth."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "(Should I have said Pony there, I wonder...)"  },
{   EV_T_SNDBCK, EV_T_SNDBCK2, PP_PHOENIX  | CMD_CHANGEPROMPT, ""  }, // update target of SNDBCK since we know the name now
{   EV_T_CRIME,  13, PP_PHOENIX  | CMD_ADDPROMPT,"What was the crime?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "No, it's not that. It's my friend... I know she is not guilty but she is going to be punished for a crime she didn't even commit."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_SELPROMPT,""  },

{  EV_T_CRIME,   13, PP_PHOENIX  | CMD_NONE,     "What kind of crime is she being accused of?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Murder..."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "(Surprise, surprise...)"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Murder never happens in Ponyville, or Equestria for that matter, so the punishment is very severe."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "What is the punishment?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Banishment..."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Well that isn't so bad compared to-"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "To the moon... or even the sun..."  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "I have convinced the Princess to go easy on her but she will have no choice if the verdict ends up being guilty."  },
{   EV_T_DETAIL, 9,  PP_PHOENIX  | CMD_ADDPROMPT,"Any details?"  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "(And forget what I just said, sheesh! If being sent to the sun is \"going easy on someone\" then remind me never to do anything bad in this place.)"  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_SELPROMPT,""  },

{   EV_T_DETAIL, 13, PP_PHOENIX  | CMD_NONE,     "So...uh...Twilight, do you know any details about the crime?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "Not much, all I know was my friend was near the scene of the crime when the murder took place. That is why she's the prime suspect."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Where is she right now?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "In the Ponyville Detention Center."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Have you spoken with her since?"  },
{   EV_NONE,     5 , PP_TWILIGHT | CMD_NONE,     "I would but the guards won't let me in."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_NONE,     "They won't let you in? Why not?"  },
{   EV_NONE,     13, PP_TWILIGHT | CMD_NONE,     "I can only get in there with a Defense Attorney which is why I was trying to call one."  },
{   EV_NONE,     13, PP_PHOENIX  | CMD_NONE,     "Okay then. Since I'm a Defense Attorney, let's go to this Detention Center."  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_MUSTRUCY, "Really! So you'll take the case?!"  },
{   EV_NONE,     6 , PP_PHOENIX  | CMD_NONE,     "Hey hey... I haven't decided that yet. I just thought the least I could do is help you get in to speak with your friend."  },
{   EV_NONE,     6 , PP_TWILIGHT | CMD_NONE,     "Thank you for your kindness, Phoenix Wright."  },
{   EV_NONE,     5 , PP_PHOENIX  | CMD_STOPMUS,  "How did you know my name? I haven't introduced myself yet..."  },
{   EV_NONE,     16, PP_TWILIGHT | CMD_NONE,     "Oh-uh... I did... uh.. a quick identification spell."  },
{   EV_NONE,     16, PP_PHOENIX  | CMD_NONE,     "Identification spell?"  },
{   EV_NONE,     10, PP_TWILIGHT | CMD_NONE,     "Yeah! An identification spell! Anyway, let me prepare a few things, then we can go to the Detention Center."  },
{   EV_NONE,     4,  PP_PHOENIX  | CMD_NONE,     "(After I get her inside there with her friend, I'll let her off easy and make her send me back home. There is no way I'm taking a case this weird...)"  },
{   2,           4 , PP_PHOENIX  | CMD_ENDSTORY, ""  }
};

#endif

#ifdef LOCATION_IS_2
//      story                                    //  0                               1                               2                               3                               4                               5                               6                               7
const Story_t story[] =  {                       //  0123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901012345678901234567890123456789010123456789012345678901234567890101234567890123456789012345678901
{   EV_NONE,    17,     PP_NONE     | CMD_NONE,     "Ponyville June 9th, 10:05PM"   },
{   EV_NONE,    17,     PP_PHOENIX  | CMD_NONE,     "I have never felt like such a minority in my life!"    },
{   EV_NONE,    18,     PP_TWILIGHT | CMD_NONE,     "Oh, it wasn't that bad."   },
{   EV_NONE,    18,     PP_PHOENIX  | CMD_NONE,     "All those ponies were gawking at me the whole way here!"   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_NONE,     "Mr. Wright, humans have almost never been seen in Equestria."   },
{   EV_NONE,    18,     PP_TWILIGHT | CMD_NONE,     "In fact you may be the first one in Ponyville."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "You should be honored!"   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_NONE,     "(Honored? Strolling around a town infested with candy colored equines...)"   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_NONE,     "(Yeah, maybe I'd feel honored if I was... Oh, I dunno... a five year old girl!)"   },

{   EV_T_HUMAN, 20,     PP_PHOENIX  | CMD_ADDPROMPT, "How did you know?"  },
{   EV_T_NOHUMAN, 20,   PP_PHOENIX  | CMD_ADDPROMPT, "Let it go"  },
{   EV_NONE,     20,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_HUMAN, 20,     PP_PHOENIX  | CMD_NONE,     "So how did you know I was a human?"   },
{   EV_NONE,    21,     PP_TWILIGHT | CMD_NONE,     "I read a lot!"   },
{   EV_NONE,    21,     PP_TWILIGHT | CMD_NONE,     "I've read almost every book in my library five times over and I am familiar with a lot of different species:"   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "Chimeras, Trolls, Basilisks, Goblins, et cetera, et cetera."   },
{   EV_NONE,    20,     PP_PHOENIX  | CMD_NONE,     "(Wait!? You're telling me she has read every book in that gigantic library FIVE TIMES?!)"   },

{   EV_T_NOHUMAN, 19,   PP_TWILIGHT | CMD_NONE,     "Anyway we're here, Phoenix."   },
{   PP_GUARD,   22,     PP_GUARD    | CMD_ADDEV,    "Halt! Only a lawyer can enter the detention center."   },
{   EV_NONE,    18,     PP_TWILIGHT | CMD_NONE,     "Well, go on..."   },
{   EV_NONE,    22,     PP_PHOENIX  | CMD_NONE,     "Uh... Hi guys, I'm a lawyer..."   },
{   EV_NONE,    22,     PP_GUARD    | CMD_NONE,     "Identification!"   },

{   EV_NONE,    22,     PP_GUARD    | CMD_SHOWEV,   "Present your identification"   },
{   EV_BADGE,EV_T_LAWYERBADGE, PP_GUARD|CMD_JUMPIFSHOW, "" }, 
{  EV_E_BADGE,EV_T_RIGHTBADGE, PP_GUARD|CMD_JUMPIFSHOW, "" }, 
{   EV_T_NOBADGE,22,    PP_GUARD    | CMD_JUMP,     "" }, 

{   EV_T_LAWYERBADGE, 22, PP_PHOENIX| CMD_NONE,     "Ah!... Right here!"   },
{   EV_NONE,    23,     PP_PHOENIX  | CMD_NONE,     "(Never leave home without it!)"   },
{   EV_NONE,    23,     PP_GUARD    | CMD_NONE,     "What is that?"   },
{   EV_NONE,    23,     PP_GUARD    | CMD_NONE,     "Is that a toy? You look a little old to be playing with toys."   },
{   EV_NONE,    23,     PP_PHOENIX  | CMD_NONE,     "(Next time I am leaving it at home...)"   },

{   EV_T_NOBADGE,22,    PP_GUARD    | CMD_NONE,     "You cannot pass without valid Equestrian identification."   },
{   EV_NONE,    22,     PP_PHOENIX  | CMD_NONE,     "But I don't have any..."   },
{   EV_NONE,    22,     PP_GUARD    | CMD_NONE,     "Then beat it Spiky!"   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE,     "Twilight! They're not letting me in."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "Oh that's right, Mr. Wright! I was supposed to give you this."   },
{   EV_NONE,    24,     PP_TWILIGHT | CMD_CLRPROMPT,"The princess ordered me to give you this earlier today. A permit to defend in Equestria."   },

{   EV_T_QUESTIONBADGE,24,PP_PHOENIX| CMD_ADDPROMPT,"That seems odd..."   },
{   EV_T_NOQBADGE,24,   PP_PHOENIX | CMD_ADDPROMPT, "That's fine."        },
{   EV_NONE,     24,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{EV_T_QUESTIONBADGE,24, PP_PHOENIX  | CMD_NONE,     "I see... wait..."   },
{   EV_NONE,    25,     PP_PHOENIX  | CMD_NONE,     "I thought you accidentally brought me here. How could your princess have had that prepared for me?"   },
{   EV_NONE,    26,     PP_TWILIGHT | CMD_NONE,     "O-oh uh What I meant was... I had my assistant Spike prepare it before we left."   },
{   EV_NONE,    26,     PP_PHOENIX  | CMD_NONE,     "Spike? I didn't see anyone else in that library..."   },
{   EV_NONE,    25,     PP_TWILIGHT | CMD_NONE,     "He was sleeping. It's late as you can see, I had to wake him up and have him prepare it. That's why it took a little while to leave."   },
{   EV_NONE,    27,     PP_TWILIGHT | CMD_NONE,     "I'll properly introduce you to him later."   },
{   EV_NONE,    28,     PP_PHOENIX  | CMD_NONE,     "You prepared a permit in twenty minutes? I find that a little fishy..."   },
{   EV_NONE,    29,     PP_TWILIGHT | CMD_NONE,     "Save the questions for my friend, just take the badge!"   },
{   EV_NONE,    29,     PP_PHOENIX  | CMD_NONE,     "(This isn't helping me accept your request, you know...)"   },

{ EV_T_NOQBADGE,30,     PP_PHOENIX  | CMD_CHIMESFX, "Equestrian Attorney Badge. A heart shaped badge that gives all the privileges of an Equestrian defense attorney."  },
{ EV_E_BADGE,   19,     PP_PHOENIX  | CMD_ADDEV,    "A heart..."   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE,     "(I feel my masculinity going... going... gone.)"   },
{   EV_NONE,    31,     PP_TWILIGHT | CMD_NONE,     "Come on, hurry up! Visiting hours are almost over."   },
{   EV_NONE,    31,     PP_PHOENIX  | CMD_NONE,     "Alright, alright! No need to shove me..."   },
{   EV_NONE,    32,     PP_PHOENIX  | CMD_NONE,     "Okay... guys here it is..."   },
{   EV_NONE,    32,     PP_PHOENIX  | CMD_NONE,     "(This is so degrading...)"   },

{ EV_T_RIGHTBADGE,32,   PP_GUARD    | CMD_NONE,     "Permission granted, you may enter."   },
{   EV_NONE,    32,     PP_PHOENIX  | CMD_NONE,     "Phew... alrighty!"   },
{   EV_NONE,    19,     PP_PHOENIX  | CMD_NONE,     "Come on Twilight, you can go speak with your friend now."   },
{   EV_NONE,    33,     PP_TWILIGHT | CMD_NONE,     "Sorry Phoenix..."   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "Sorry? About what?"   },
{   EV_NONE,    33,     PP_TWILIGHT | CMD_NONE,     "I am not allowed in, only attorneys are allowed to speak with suspects..."   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "But you said..."   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_NONE,     "I know I said I'd talk to her but it'd be better if you got all the details about the crime to make your judgement."   },
{   EV_NONE,    19,     PP_TWILIGHT | CMD_NONE,     "Just please hear her out... if you don't want to do it after that..."   },
{   EV_NONE,    33,     PP_TWILIGHT | CMD_NONE,     "I'll send you back to where you came from..."   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_CLRPROMPT, "But I-"   },

{   EV_T_CONCERN,24,    PP_PHOENIX  | CMD_ADDPROMPT, "Concerned..."   },
{   EV_T_NOCONCERN,24,  PP_PHOENIX  | CMD_ADDPROMPT, "See what it's all about."        },
{   EV_NONE,     24,    PP_PHOENIX  | CMD_SELPROMPT, ""  },

{   EV_T_CONCERN, 33,   PP_PHOENIX  | CMD_NONE,     "(Should I really be doing this...?)"   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "(Should I really be meddling in some other world's affair...?)"   },
{   EV_NONE,    33,     PP_PHOENIX  | CMD_NONE,     "(Maybe I should at least hear what all this fuss is about...)"   },

{ EV_T_NOCONCERN, 33,   PP_PHOENIX  | CMD_NONE,     "Sigh... Fine..."   },
{   EV_NONE,    20,     PP_TWILIGHT | CMD_NONE,     "Thank you so much, Mr. Wright."   },
{   3,          20,     PP_NONE     | CMD_ENDSTORY, ""  }   // go to location 3

};
#endif

#ifndef LOCATION_IS_LOADER
// a value that can be referenced externally, though I don't plan to check everything
int nStorySize = sizeof(story)/sizeof(story[0]);
#endif

